### ISSUE TITLE
yarn：src/utils/attach-abi.ts(4,44): error TS2307

### ISSUE THREAD

**Issue by jwbda** [OpenZeppelin/openzeppelin-upgrades#1014]
Hi，when I clone the project to local, run `yarn` command, and the error show bellow. Please help to resolve this. Any reply would be appreciated. 🙏🏻️
```txt
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
$ wsrun -ms prepare && tsc -b
@openzeppelin/upgrades-core
yarn run v1.22.22
$ yarn clean && yarn compile && yarn copyfiles
$ hardhat clean && rimraf dist *.tsbuildinfo
$ tsc -b && yarn compile:contracts
$ hardhat compile
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/cli/Validate.sol:14:5:
 |    |
 | 14 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/cli/Validate.sol:44:5:
 |    |
 | 44 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/cli/Validate.sol:49:5:
 |    |
 | 49 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/cli/Validate.sol:97:5:
 |    |
 | 97 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |    --> contracts/test/cli/Validate.sol:119:5:
 |     |
 | 119 |     selfdestruct(payable(msg.sender));
 |     |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |    --> contracts/test/cli/Validate.sol:140:5:
 |     |
 | 140 |     selfdestruct(payable(msg.sender));
 |     |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/ValidationsNatspec.sol:69:5:
 |    |
 | 69 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/ValidationsNatspec.sol:76:5:
 |    |
 | 76 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |   --> contracts/test/ValidationsNatspec.sol:83:5:
 |    |
 | 83 |     selfdestruct(payable(msg.sender));
 |    |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |    --> contracts/test/ValidationsNatspec.sol:139:5:
 |     |
 | 139 |     selfdestruct(payable(msg.sender));
 |     |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: "selfdestruct" has been deprecated. The underlying opcode will eventually undergo breaking changes, and its use is not recommended.
 |    --> contracts/test/ValidationsNatspec.sol:147:5:
 |     |
 | 147 |     selfdestruct(payable(msg.sender));
 |     |     ^^^^^^^^^^^^
 | 
 | 
 | Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
 |   --> contracts/test/Proxiable.sol:11:58:
 |    |
 | 11 |     function upgradeToAndCall(address newImplementation, bytes calldata data) external {
 |    |                                                          ^^^^^^^^^^^^^^^^^^^
 | 
 | 
 | Compiled 90 Solidity files successfully (evm targets: istanbul, london, paris).
$ node scripts/copy-build-info-v5.js && bash scripts/copy-legacy-artifacts.sh
 | scripts/copy-legacy-artifacts.sh: line 10: jq: command not found
 | Error: @openzeppelin/upgrades-core must depend on a previous version of itself at version 1.31.3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn prepare` failed with exit code 1
@openzeppelin/hardhat-upgrades
yarn run v1.22.22
$ yarn clean && yarn compile
$ rimraf dist *.tsbuildinfo
$ tsc -b
 | src/utils/attach-abi.ts(4,44): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol/ITransparentUpgradeableProxy.json' or its corresponding type declarations.
 | src/utils/attach-abi.ts(7,26): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol/ProxyAdmin.json' or its corresponding type declarations.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn prepare` failed with exit code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ericglau** [comment]
Can you share what happens if you just run `yarn install` from the root of this project?  See https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/CONTRIBUTING.md

**Comment by ericglau** [comment]
I notice this error in your output:
```
scripts/copy-legacy-artifacts.sh: line 10: jq: command not found
```
Can you try installing the `jq` command from https://jqlang.github.io/jq/ and try again?

**Comment by jwbda** [comment]
> Can you try installing the jq command from https://jqlang.github.io/jq/ and try again?

Sure, you are right. And I install jq through `sudo apt install jq -y`， and the problem solved. Thanks you.

And IMHO, why don't you use pnpm in all OpenZeppelin's project ?

I konw dependency of `@openzeppelin/contracts` in root project when use `yarn`.  And I think it is a little weird that `packages/core/node_modules` not have `@openzeppelin/contracts` dependency but it show in the `packages/core/package.json` file.  And `node_modules` matches `package.json` when use pnpm.

**Comment by jwbda** [comment]
It is really strange that has error when I run the same command `git clone https://github.com/OpenZeppelin/openzeppelin-upgrades.git && git reset --hard 20f02079039a814b1220ead53c1ec5744645cd05 && yarn install` again, here is the result:

```shell
yarn install
```

```text
yarn install v1.22.22
[1/4] Resolving packages...
[2/4] Fetching packages...
warning @frangio/servbot@0.2.5: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > @openzeppelin/hardhat-upgrades@3.0.5" has unmet peer dependency "@nomicfoundation/hardhat-ethers@^3.0.0".
warning " > @openzeppelin/hardhat-upgrades@3.0.5" has unmet peer dependency "hardhat@^2.0.2".
[4/4] Building fresh packages...
$ wsrun -ms prepare && tsc -b
@openzeppelin/upgrades-core
yarn run v1.22.22
$ yarn clean && yarn compile && yarn copyfiles
$ hardhat clean && rimraf dist *.tsbuildinfo
 | Hardhat config is returning an empty config object, check the export from the config file if this is unexpected.
 | 
 | Learn more about configuring Hardhat at https://hardhat.org/config
 | 
$ tsc -b && yarn compile:contracts
$ hardhat compile
 | Hardhat config is returning an empty config object, check the export from the config file if this is unexpected.
 | 
 | Solidity compiler is not configured. Version 0.7.3 will be used by default. Add a 'solidity' entry to your configuration to suppress this warning.
 | 
 | Learn more about compiler configuration at https://hardhat.org/config
 | 
 | Nothing to compile
$ node scripts/copy-build-info-v5.js && bash scripts/copy-legacy-artifacts.sh
 | node:fs:453
 |     return binding.readFileUtf8(path, stringToFlags(options.flag));
 |                    ^
 | 
 | Error: ENOENT: no such file or directory, open 'artifacts/@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol/ERC1967Proxy.dbg.json'
 |     at Object.readFileSync (node:fs:453:20)
 |     at readJSON (/home/develop/test/c/openzeppelin-upgrades/packages/core/scripts/copy-build-info-v5.js:7:24)
 |     at Object.<anonymous> (/home/develop/test/c/openzeppelin-upgrades/packages/core/scripts/copy-build-info-v5.js:24:24)
 |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
 |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
 |     at Module.load (node:internal/modules/cjs/loader:1207:32)
 |     at Module._load (node:internal/modules/cjs/loader:1023:12)
 |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
 |     at node:internal/main/run_main_module:28:49 {
 |   errno: -2,
 |   code: 'ENOENT',
 |   syscall: 'open',
 |   path: 'artifacts/@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol/ERC1967Proxy.dbg.json'
 | }
 | 
 | Node.js v20.11.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn prepare` failed with exit code 1
@openzeppelin/hardhat-upgrades
yarn run v1.22.22
$ yarn clean && yarn compile
$ rimraf dist *.tsbuildinfo
$ tsc -b
 | src/utils/attach-abi.ts(3,44): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/transparent/TransparentUpgradeableProxy.sol/ITransparentUpgradeableProxy.json' or its corresponding type declarations.
 | src/utils/attach-abi.ts(4,44): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol/ITransparentUpgradeableProxy.json' or its corresponding type declarations.
 | src/utils/attach-abi.ts(6,26): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/transparent/ProxyAdmin.sol/ProxyAdmin.json' or its corresponding type declarations.
 | src/utils/attach-abi.ts(7,26): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol/ProxyAdmin.json' or its corresponding type declarations.
 | src/verify-proxy.ts(14,32): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/build-info-v5.json' or its corresponding type declarations.
 | src/verify-proxy.ts(18,26): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/ERC1967/ERC1967Proxy.sol/ERC1967Proxy.json' or its corresponding type declarations.
 | src/verify-proxy.ts(19,25): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/beacon/BeaconProxy.sol/BeaconProxy.json' or its corresponding type declarations.
 | src/verify-proxy.ts(20,31): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/beacon/UpgradeableBeacon.sol/UpgradeableBeacon.json' or its corresponding type declarations.
 | src/verify-proxy.ts(21,41): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/transparent/TransparentUpgradeableProxy.sol/TransparentUpgradeableProxy.json' or its corresponding type declarations.
 | src/verify-proxy.ts(22,24): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/transparent/ProxyAdmin.sol/ProxyAdmin.json' or its corresponding type declarations.
 | src/defender/deploy.ts(19,32): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/build-info-v5.json' or its corresponding type declarations.
 | src/defender/deploy.ts(21,26): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/ERC1967/ERC1967Proxy.sol/ERC1967Proxy.json' or its corresponding type declarations.
 | src/defender/deploy.ts(22,25): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/beacon/BeaconProxy.sol/BeaconProxy.json' or its corresponding type declarations.
 | src/defender/deploy.ts(23,31): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/beacon/UpgradeableBeacon.sol/UpgradeableBeacon.json' or its corresponding type declarations.
 | src/defender/deploy.ts(24,41): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/transparent/TransparentUpgradeableProxy.sol/TransparentUpgradeableProxy.json' or its corresponding type declarations.
 | src/utils/factories.ts(3,26): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/ERC1967/ERC1967Proxy.sol/ERC1967Proxy.json' or its corresponding type declarations.
 | src/utils/factories.ts(4,25): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/beacon/BeaconProxy.sol/BeaconProxy.json' or its corresponding type declarations.
 | src/utils/factories.ts(5,31): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/beacon/UpgradeableBeacon.sol/UpgradeableBeacon.json' or its corresponding type declarations.
 | src/utils/factories.ts(6,41): error TS2307: Cannot find module '@openzeppelin/upgrades-core/artifacts/@openzeppelin/contracts-v5/proxy/transparent/TransparentUpgradeableProxy.sol/TransparentUpgradeableProxy.json' or its corresponding type declarations.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn prepare` failed with exit code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by ericglau** [comment]
Regarding pnpm, we haven't had a need to switch from yarn for this project.

Regarding your build error, the output above has the following in the `hardhat compile` step in `packages/core`:
```
$ hardhat compile
 | Hardhat config is returning an empty config object, check the export from the config file if this is unexpected.
 | 
 | Solidity compiler is not configured. Version 0.7.3 will be used by default. Add a 'solidity' entry to your configuration to suppress this warning.
 | 
 | Learn more about compiler configuration at https://hardhat.org/config
 | 
 | Nothing to compile
```
This is causing that step to not do anything, which leads to the later failures.  It might be an environment or configuration issue.

**Comment by jwbda** [comment]
Hi, @ericglau thanks for your patient reply. and I make the local develop environment exactly like the [this](https://github.com/OpenZeppelin/openzeppelin-upgrades/actions/runs/8711593917/job/23896035230). And multiple tests. Finally  the weird problem is gone.
