### ISSUE TITLE
An error due to function defined in struct in library

### ISSUE THREAD

**Issue by liuhp1130** [OpenZeppelin/openzeppelin-upgrades#1031]
This is my library 

    struct Array {
        Elem[] _elems;
        function(Elem memory, Elem memory) internal pure returns (ebool) _Compare;
        function(ebool, Elem storage, Elem storage) internal _SwapIf;
    }

This is an error

```
Error: An unexpected condition occurred. Please report this at https://zpl.in/upgrades/report
      at assert (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/utils/assert.ts:7:11)
      at StorageLayoutComparator.getVisibilityChange (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:194:11)
      at StorageLayoutComparator.uncachedGetTypeChange (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:287:19)
      at StorageLayoutComparator.getTypeChange (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:273:27)
      at StorageLayoutComparator.getFieldChange (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:208:12)
      at /Users/lhp/git-project/CommodityTrading/node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:152:63
      at change (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/levenshtein.ts:86:20)
      at buildMatrix (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/levenshtein.ts:55:29)
      at levenshtein (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/levenshtein.ts:25:18)
      at StorageLayoutComparator.layoutLevenshtein (node_modules/.pnpm/@openzeppelin+upgrades-core@1.33.1/node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:152:28)
```

**Comment by Amxx** [comment]
Hello @liuhp1130 

Thank you for raising this issue. Could you provide a minimal reproductible example?

Does this happen when doing an initial deployment? An upgrade? Would you be able to a complete description of the steps to reproduce this bug?

**Comment by liuhp1130** [comment]
> 你好@liuhp1130
> 
> 感谢您提出这个问题。您能提供一个最小可重现的示例吗？
> 
> 初始部署时会发生这种情况吗？升级时？您能完整描述重现此错误的步骤吗？

Thank you very much for your reply! I'm very sorry for not describing it clearly. 
This is an error that occurs when upgrading and does not appear during initial deployment.

Below is my reproducible example.

My SortedArray.sol
```
// SPDX-License-Identifier: BSD-3-Clause-Clear

pragma solidity ^0.8.20;

import "fhevm/lib/TFHE.sol";

library SortedArray {
    struct Bid {
        euint32 price;
        euint32 portion;
    }

    struct Elem {
        euint32 key;
        Bid bid;
    }

    struct Array {
        Elem[] _elems;
        function(Elem memory, Elem memory) internal pure returns (ebool) _Compare;
        function(ebool, Elem storage, Elem storage) internal _SwapIf;
    } 
}
```

My MyContract.sol

```
pragma solidity ^0.8.20;


import "./SortedArray.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";

using SortedArray for SortedArray.Array;

contract MyContract is Initializable {
    uint256 public x;
    SortedArray.Array private _sortedArray;

    function initialize(uint256 _x) public initializer {
        x = _x;
        _sortedArray._Compare =  _compareSell;
        _sortedArray._SwapIf = _swapIf;
    }

    function initFn() public view virtual returns(string memory){
        return "this is init output";
    }

    function _compareSell(
        SortedArray.Elem memory a,
        SortedArray.Elem memory b
    ) private pure returns (ebool) {
        return TFHE.gt(a.key, b.key);
    }

    function _swapIf(
        ebool cond,
        SortedArray.Elem storage a,
        SortedArray.Elem storage b
    ) private {
        SortedArray.Elem memory c = SortedArray.Elem(a.key, a.bid);
        a.key = TFHE.select(cond, b.key, c.key);
        b.key = TFHE.select(cond, c.key, b.key);
    }
}
```

My MyContract2.sol
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "./MyContract.sol";

contract MyContract2 is MyContract {
    uint256 public y;

     function upgradeTest(uint256 _x) public view virtual returns(uint256){
        return y + _x;
    }
}
```
My test file: test.ts

```
import { expect } from 'chai';
import { ethers } from 'hardhat';

import { createInstances } from '../instance';
import { getSigners, initSigners } from '../signers';
import { deployFixtureProxy } from '../deploy';
import { upgradeFixture } from '../upgrade'

describe('MyContract', function () {
    before(async function () {
      await initSigners(2);

      this.signers = await getSigners();
    });
  
    beforeEach(async function () {
      const contract = await deployFixtureProxy('MyContract',66);
      this.contractAddress = await contract.getAddress();
      this.erc20 = contract;
      this.instances = await createInstances(this.contractAddress, ethers, this.signers);
    });

    it('initialize Contract',async function (){
        const initRes = await this.erc20.initFn()
        expect(initRes).to.equal("this is init output")
    })


    it('upgrade Contract',async function (){ 
        const upgradeContract =  await upgradeFixture('MyContract2',this.contractAddress)
        console.log('upgrade===',upgradeContract)
        this.erc20 = upgradeContract
        const upgradeRes = await this.erc20.upgradeTest(66)
        expect(upgradeRes).to.equal(66);
        const initRes = await this.erc20.initFn()
        expect(initRes).to.equal("this is init output")
    })

})
```

**Comment by liuhp1130** [comment]
> Thank you for all the details. We'll look into it!
> 
> My fear is that fn pointers are not supported by the "storage layout comparaison algorithm". During initial deployment the data is extracted correctly, but then during the upgrade, the comparaison doesn't really know how to check that. Maybe there is an option you could use to silent that.
> 
> @ericglau ?
> 
> For the record I think all fn pointers are stored using 32 bytes (address + selector for external, some jump pointer for internal, ...)

Thank you very much for your help, I tested it and found that the error disappeared! 

First, I tried using the `kind` and then the `unsafeAllow` options, but neither worked. Finally, using `unsafeSkipStorageCheck`, it actually passed.

Here are the files I changed: uprade.ts. 
```
import { ethers, upgrades  } from 'hardhat';

export async function upgradeFixture(newContractName: string, deployedAddress: string) {
  const contractFactory = await ethers.getContractFactory(newContractName);
  const upgradeContract = await upgrades.upgradeProxy(deployedAddress, contractFactory,{
    unsafeSkipStorageCheck: true
  });
  console.log(`${newContractName} upgraded at ${upgradeContract.target}`);
  return upgradeContract
}
```

**Comment by ericglau** [comment]
Hi @liuhp1130, we are working on a fix for the original error so that you won't need to use `unsafeSkipStorageCheck`.

However, please note that your implementation's usage of internal function pointers may not be upgrade safe.  As described in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/555, internal function pointers are no longer valid after an upgrade.  To get around this, you can either declare those functions as external, or re-assign the functions in your struct during the upgrade by using a [reinitializer](https://docs.openzeppelin.com/contracts/5.x/api/proxy#Initializable).

For example, your MyContract2.sol could have something like:
```
    function initializeV2() reinitializer(2) public {
        _sortedArray._Compare =  _compareSell;
        _sortedArray._SwapIf = _swapIf;
    }
```
And your upgrade script could have something like:
```
const upgradeContract = await upgrades.upgradeProxy(deployedAddress, contractFactory,{
    unsafeSkipStorageCheck: true,
    call: 'initializeV2',
  });
```

**Comment by liuhp1130** [comment]
> 你好@liuhp1130，我们正在修复原始错误，以便您无需使用`unsafeSkipStorageCheck`。
> 
> 但是，请注意，您的实现对内部函数指针的使用可能不安全。如[#555所述，内部函数指针在升级后不再有效。为了解决这个问题，您可以将这些函数声明为外部函数，或者在升级期间使用](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/555)[重新初始化程序](https://docs.openzeppelin.com/contracts/5.x/api/proxy#Initializable)重新分配结构中的函数。
> 
> 例如，您的 MyContract2.sol 可能包含以下内容：
> 
> ```
>     function initializeV2() reinitializer(2) public {
>         _sortedArray._Compare =  _compareSell;
>         _sortedArray._SwapIf = _swapIf;
>     }
> ```
> 
> 你的升级脚本可能包含如下内容：
> 
> ```
> const upgradeContract = await upgrades.upgradeProxy(deployedAddress, contractFactory,{
>     unsafeSkipStorageCheck: true,
>     call: 'initializeV2',
>   });
> ```

OK, thank you for your suggestion.
