### ISSUE TITLE
Test with Solidity 0.4

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#190]
A user (I think it was @mod) reported issues using a contract that had been compiled with Solidity 0.4. This may be due to Solidity or an older version of Truffle.

```
TypeError: Cannot read property 'evm' of undefined
      at Object.validate (node_modules/@openzeppelin/upgrades-core/src/validate.ts:73:77)
      at Object.validateArtifacts (node_modules/@openzeppelin/truffle-upgrades/src/validate.ts:16:10)
      at deployProxy (node_modules/@openzeppelin/truffle-upgrades/src/deploy-proxy.ts:28:23)
      at Context.<anonymous> (test/Box.proxy.test.js:13:16)
```

**Comment by julianmrodri** [comment]
I ran some initial tests and can confirm at least that the Truffle plugin tests work fine for versions >= `0.4.22` and <= `0.4.26` (latest release).  I was able to run the provided tests smoothly using Truffle `v5.1.47`.  

To test prior versions of Solidity we would need to do some changes to the contracts,  I did a few tests adapting some of them but couldn't get the error mentioned in this issue so far. 

Further testing needs to be performed but if we have additional details about in which situation this error occurred would be great. Do we have a link to the reported details?

**Comment by frangio** [comment]
@julianmrodri Thanks for testing this! I have no more details of how the error occurred, but they did imply that it was an old artifact that had been in the repository. I'm thinking perhaps it had been generated by Truffle v4, though they didn't specify.

**Comment by julianmrodri** [comment]
Ok will look into downgrading to `Truffle v4`.  I see it more likely coming from that than from the Solidity version.

**Comment by gpersoon** [comment]
I had the same problem and was able to reproduce it in the following way:

slots.sol:
```JS
pragma solidity ^0.6.0;
contract Slots { function test() external view returns (uint) { return 1; } }
interface Oracle{ function test() external view returns (uint); }
```

Oracle.sol:
```js
pragma solidity ^0.6.0;
contract Oracle { function test() external view returns (uint) { return 1; }}
```

2_slots_deploy.js
```js
const { deployProxy } = require(’@openzeppelin/truffle-upgrades’);
var Slots = artifacts.require(“slots”);
module.exports = async function (deployer) { const SlotsS = await deployProxy(Slots,  ,{ deployer }); }
```
And the run truffle migrate twice.
The first time i see error: “Oracle” is an abstract contract or an interface and cannot be deployed.
The second time: TypeError: Cannot read property ‘evm’ of undefined
