### ISSUE TITLE
hardhat-upgrades | Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by drbullock** [OpenZeppelin/openzeppelin-upgrades#246]
I am getting this error when compiling my contracts with Hardhat:

```
TypeError: Cannot read property 'object' of undefined
    at Object.validate (C:\Token\node_modules\@openzeppelin\upgrades-core\src\validate.ts:79:32)
    at OverriddenTaskDefinition._action (C:\Token\node_modules\@openzeppelin\hardhat-upgrades\src\index.ts:19:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Environment._runTaskDefinition (C:\Token\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Token\node_modules\hardhat\src\internal\core\runtime-environment.ts:130:14)
    at SimpleTaskDefinition.action (C:\Token\node_modules\hardhat\src\builtin-tasks\compile.ts:964:37)
    at Environment._runTaskDefinition (C:\Token\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Token\node_modules\hardhat\src\internal\core\runtime-environment.ts:130:14)
    at SimpleTaskDefinition.action (C:\Token\node_modules\hardhat\src\builtin-tasks\compile.ts:395:45)
    at Environment._runTaskDefinition (C:\Token\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
```

Environment:

```
hardhat --version 2.0.4
@openzeppelin/hardhat-upgrades@1.4.0
@openzeppelin/upgrades-core@1.4.0
```

**Comment by drbullock** [comment]
Update: This is unrelated to Openzeppelin, this is an issue with hardhat I guess.

**Comment by frangio** [comment]
@drbullock Are you sure this is an issue in Hardhat? Is your project open source so I can look at the contracts that you were compiling?

**Comment by drbullock** [comment]
Hi @frangio I commented also on Hardhat Issue, here https://github.com/nomiclabs/hardhat/issues/1070#issuecomment-750890052

**Comment by frangio** [comment]
Fixed by https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/253
