### ISSUE TITLE
Hardhat deploy on xDAI “TransactionMinedTimeout [Error]: Timed out waiting for transaction” txhash doesnt exist

### ISSUE THREAD

**Issue by jacobrosenthal** [OpenZeppelin/openzeppelin-upgrades#292]
Originally reported https://forum.openzeppelin.com/t/hardhat-deploy-on-xdai-transactionminedtimeout-error-timed-out-waiting-for-transaction/5614

Im running like `DEBUG=* hardhat --network xdai run scripts/deploy.ts`

scripts/deploy.ts
```
...

  const W = await ethers.getContractFactory("W");
  const w = await upgrades.deployProxy(W, [
    d.address,
    !isDev,
  ]);
  await w.deployed();

  const DFT = await ethers.getContractFactory("DFT");
  const dfT = await upgrades.deployProxy(DFT, [], {
    initializer: false,
    unsafeAllowCustomTypes: true,
  });
  await dfT.deployed();

 const DFU = await ethers.getContractFactory("DFU");
  const dfU = await DFU.deploy();
  await dfU.deployed();

  const LU = await ethers.getContractFactory("DFLU");
  const lU = await LU.deploy();
  await lU.deployed();

  const DFP = await ethers.getContractFactory("DFP", {
    libraries: {
      DFLU: lU.address,
      DFU: dfU.address,
    },
  });
  const dfP = await DFP.deploy();
  await dfP.deployed();

  const DFI = await ethers.getContractFactory("DFI");
  const dfI = await DFI.deploy();
  await dfI.deployed();

  const V = await ethers.getContractFactory("V");
  const v = await V.deploy();
  await v.deployed();

  const DFC = await ethers.getContractFactory("DFC", {
    libraries: {
      DFI: dfI.address,
      DFP: dfP.address,
      DFU: dfU.address,
      V: v.address,
    },
  });

  const dFC = await upgrades.deployProxy(
    DFC,
    [d.address, w.address, dfT.address, DISABLE_ZK_CHECKS],
    { unsafeAllowCustomTypes: true, unsafeAllowLinkedLibraries: true }
  );
  await dFC.deployed();
 
 ...
```

hardhat.config.ts
```
const config: HardhatUserConfig = {
  defaultNetwork: "hardhat",
  networks: {
    xdai: {
      url: "https://rpc.xdaichain.com/",
      accounts: {
        mnemonic: MNEMONIC,
      },

    },
    localhost: {
      url: "http://localhost:8545/",
      accounts: {
        mnemonic: MNEMONIC,
        accountsBalance: "10000000000000000000000",
      },
    },
    hardhat: {
      accounts: [
...
      ],
    },
  },
  solidity: {
    version: "0.6.9",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
};
export default config;
```

Versions
```
    "@nomiclabs/hardhat-ethers": "^2.0.1",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts-upgradeable": "^3.3.0",
    "@openzeppelin/hardhat-upgrades": "^1.5.0",
    "hardhat": "^2.0.7",
    "hardhat-typechain": "^0.3.4",
```

the contract 0xE86FB472D997bD489EEd806f6b138518d5473De0 will exist on blockscout, but that transaction hash its looking for wont?!
```
 You are using the `unsafeAllowLinkedLibraries` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

  @openzeppelin:upgrades:core fetching deployment of implementation f3b04f614a3a1e805085ed0d5729854e07fa045ae4fbaf7bd7a23d8ca77e0e3a +53s
  @openzeppelin:upgrades:core deployment of implementation f3b04f614a3a1e805085ed0d5729854e07fa045ae4fbaf7bd7a23d8ca77e0e3a not found +2ms

  @openzeppelin:upgrades:core initiated deployment 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +1m
  @openzeppelin:upgrades:core verifying deployment tx mined 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +4ms
  @openzeppelin:upgrades:core waiting for deployment tx mined 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +250ms
  
  @openzeppelin:upgrades:core verifying deployment tx mined 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +5s
  @openzeppelin:upgrades:core waiting for deployment tx mined 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +223ms
...
  @openzeppelin:upgrades:core verifying deployment tx mined 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +5s
  @openzeppelin:upgrades:core waiting for deployment tx mined 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49 +221ms
TransactionMinedTimeout [Error]: Timed out waiting for transaction 0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49
    at Object.waitAndValidateDeployment (/contracts/eth/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:61:15)
    at fetchOrDeployGeneric (/contracts/eth/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:42:5)
    at Proxy.deployProxy (/contracts/eth/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:45:18) {
  deployment: {
    address: '0xE86FB472D997bD489EEd806f6b138518d5473De0',
    txHash: '0x2035336a41b178ec16035e93621acd3f0107ec20e877ff4fc2215d909c138f49',
    layout: { storage: [Array], types: [Object] }
  }
}
```

**Comment by jacobrosenthal** [comment]
Looks like this is opened so I can share the code directly

https://github.com/jacobrosenthal/eth/tree/hardhat
`yarn && yarn deploy:prod`

youll need an .env.prod with the mnemonic wallet funded
```
# deploys core and whitelist contracts
deployer_mnemonic= your mnemonic here your mnemonic here your mnemonic here

DISABLE_ZK_CHECKS=false

# if ropsten, infura project id
project_id=doesntmatter
```

**Comment by abcoathup** [comment]
Hi @jacobrosenthal,

I get the same timeout running your code:
```
$ yarn && yarn deploy:prod
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.1: The platform "linux" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ yarn run compile
yarn run v1.22.4
$ hardhat compile
Downloading compiler 0.6.9
Compiling 26 files with 0.6.9
contracts/DarkForestLazyUpdate.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

contracts/DarkForestTokens.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

contracts/Verifier.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

contracts/DarkForestPlanet.sol:253:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        DarkForestTypes.PlanetDefaultStats[] storage planetDefaultStats,
        ^-------------------------------------------------------------^

contracts/DarkForestPlanet.sol:373:9: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
        mapping(uint256 => DarkForestTypes.PlanetExtendedInfo)
        ^ (Relevant source part starts here and spans across multiple lines).

contracts/DarkForestUtils.sol:107:5: Warning: Function state mutability can be restricted to pure
    function _isPlanetMineable(uint256 planetId, uint256 planetLevel)
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/DarkForestUtils.sol:118:5: Warning: Function state mutability can be restricted to pure
    function _artifactSeed(
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/DarkForestUtils.sol:135:5: Warning: Function state mutability can be restricted to pure
    function _randomArtifactTypeAndLevelBonus(uint256 artifactSeed)
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/DarkForestUtils.sol:168:5: Warning: Function state mutability can be restricted to pure
    function _getBiome(
    ^ (Relevant source part starts here and spans across multiple lines).

contracts/DarkForestUtils.sol:182:5: Warning: Function state mutability can be restricted to pure
    function _getUpgradeForArtifact(DarkForestTypes.Artifact memory artifact)
    ^ (Relevant source part starts here and spans across multiple lines).

Compilation finished successfully
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Done in 17.18s.
Done in 42.49s.
yarn run v1.22.4
$ NODE_ENV=production hardhat --network xdai run scripts/deploy.ts
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
Whitelist deployed to: 0x8a2cd617a589A043bF85f3157AFa03107a629C4f
DarkForestTokens deployed to: 0x896B7B588A0E878351c389FC2538A9282afb4013
Warning: Potentially unsafe deployment of DarkForestCore

    You are using the `unsafeAllowLinkedLibraries` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

TransactionMinedTimeout [Error]: Timed out waiting for transaction 0xd4c7cd2c170cf73f1466d0d51766c2155c09272d875fbae050a7fbd90c19ee2e
    at Object.waitAndValidateDeployment (/home/abcoathup/projects/forum/issue/eth/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:61:15)
    at fetchOrDeployGeneric (/home/abcoathup/projects/forum/issue/eth/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:42:5)
    at Proxy.deployProxy (/home/abcoathup/projects/forum/issue/eth/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:45:18) {
  deployment: {
    address: '0xD2ff293F0120A1697d6F2fcDbEABbe249edA048C',
    txHash: '0xd4c7cd2c170cf73f1466d0d51766c2155c09272d875fbae050a7fbd90c19ee2e',
    layout: { storage: [Array], types: [Object] }
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

---

I wasn't able to reproduce with a simple example and a single library

## Answer.sol
```solidity
// contracts/Answer.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

library Answer {
    function getAnswer() public returns (uint256) {
        return 42;
    }
}
```
## Box.sol
```solidity
// contracts/Box.sol
// SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;
 
import "./Answer.sol";

contract Box {
    uint256 private value;

    // Emitted when the stored value changes
    event ValueChanged(uint256 newValue);
 
    // Stores a new value in the contract
    function store(uint256 newValue) public {
        value = newValue;
        emit ValueChanged(newValue);
    }

    function storeAnswer() public {
        store(Answer.getAnswer());
    }

    // Reads the last stored value
    function retrieve() public view returns (uint256) {
        return value;
    }
}
```

## Deploy.js
```js
// scripts/deploy.js
async function main() {
    const Answer = await ethers.getContractFactory("Answer");
    console.log("Deploying Answer...");
    const answer = await Answer.deploy();
    await answer.deployed();
    console.log("Answer deployed to:", answer.address);

    // Library linking: https://hardhat.org/plugins/nomiclabs-hardhat-ethers.html#library-linking 
    const Box = await ethers.getContractFactory("Box", {libraries: { Answer: answer.address} });
    console.log("Deploying Box...");
    const box = await upgrades.deployProxy(Box, [42], { initializer: 'store', unsafeAllowLinkedLibraries: true });
    console.log("Box deployed to:", box.address);
  }
  
  main()
    .then(() => process.exit(0))
    .catch(error => {
      console.error(error);
      process.exit(1);
    });
```
```
$ npx hardhat run --network xdai scripts/deploy.js
Compiling 2 files with 0.7.3
contracts/Answer.sol:6:5: Warning: Function state mutability can be restricted to pure
    function getAnswer() public returns (uint256) {
    ^ (Relevant source part starts here and spans across multiple lines).

Compilation finished successfully
Deploying Answer...
Answer deployed to: 0x903303BfA4Def0Fc4F474b965DC81F33CB87b550
Deploying Box...
Warning: Potentially unsafe deployment of Box

    You are using the `unsafeAllowLinkedLibraries` flag to include external libraries.
    Make sure you have manually checked that the linked libraries are upgrade safe.

Box deployed to: 0x27Bb3535432DE5351f7f892aDF99085f9cfCbfcb
```

**Comment by frangio** [comment]
Continued this conversation in the [forum thread](https://forum.openzeppelin.com/t/hardhat-deploy-on-xdai-transactionminedtimeout-error-timed-out-waiting-for-transaction/5614).
