### ISSUE TITLE
Support for Optimism Network

### ISSUE THREAD

**Issue by guanzhenxing** [OpenZeppelin/openzeppelin-upgrades#309]
I want to deploy a proxy contract at optimism network,but it not work.

My code like:
```
 let WePiggyPriceOracleV1 = await l2ethers.getContractFactory("WePiggyPriceOracleV1", {
        signer: (await ethers.getSigners())[0]
    });
    let wepiggy_price_oracle_v1 = await upgrades.deployProxy(WePiggyPriceOracleV1);
    await wepiggy_price_oracle_v1.deployed();
```
and the result is:
```
  ganache Optional dependencies installed; exporting ganache-core with native optional dependencies. +0ms
  ganache Optional dependencies installed; exporting ganache-core with native optional dependencies. +0ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Creating provider for network optimism +76ms
  @openzeppelin:upgrades:core fetching deployment of implementation 2f3b6eebb3cb5fdeebbe55176512a04c88e435fb352f67e540dcfdacef496e4c +0ms
  @openzeppelin:upgrades:core deployment of implementation 2f3b6eebb3cb5fdeebbe55176512a04c88e435fb352f67e540dcfdacef496e4c not found +1ms
  @openzeppelin:upgrades:core initiated deployment 0xc55a7af276d3f972e8eb2b6b27bdecaab32763fa2ff8eb5c9eeb940a38f52255 +12s
  @openzeppelin:upgrades:core verifying deployment tx mined 0xc55a7af276d3f972e8eb2b6b27bdecaab32763fa2ff8eb5c9eeb940a38f52255 +6ms
  @openzeppelin:upgrades:core succeeded verifying deployment tx mined 0xc55a7af276d3f972e8eb2b6b27bdecaab32763fa2ff8eb5c9eeb940a38f52255 +1s
  @openzeppelin:upgrades:core fetching deployment of proxy admin +2s
  @openzeppelin:upgrades:core deployment of proxy admin not found +1ms
  @openzeppelin:upgrades:core initiated deployment 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79 +10s
  @openzeppelin:upgrades:core verifying deployment tx mined 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79 +1ms
  @openzeppelin:upgrades:core succeeded verifying deployment tx mined 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79 +1s
{ Error: Invalid deployment with address 0xeB4cbbCE5B52ca1b167898dac418da2C68ca9c01 and txHash 0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79
    at Object.waitAndValidateDeployment (/Users/dev/piggy/piggy-contract/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:77:4)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  deployment:
   { address: '0xeB4cbbCE5B52ca1b167898dac418da2C68ca9c01',
     txHash:
      '0x58b4d994dbe5956f35a0fc073c42376e80e58cb873b79f57856dba3fffd64c79' } }
```

And I found this code at @openzeppelin/hardhat-upgrades/src/proxy-factory.ts
```
import AdminUpgradeabilityProxy from '@openzeppelin/upgrades-core/artifacts/contracts/proxy/AdminUpgradeabilityProxy.sol/AdminUpgradeabilityProxy.json';
import ProxyAdmin from '@openzeppelin/upgrades-core/artifacts/contracts/proxy/ProxyAdmin.sol/ProxyAdmin.json';
```
but the optimism use AdminUpgradeabilityProxy-ovm.json and ProxyAdmin-ovm.json . Is it a bug ? 

Thanks!

**Comment by abcoathup** [comment]
Hi @guanzhenxing!  

Unfortunately, I wasn’t able to reproduce this issue. I tried the following:
I tried to compile and test an upgradeable contract but not sure if my syntax was right for testing with Optimism: https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-hardhat/3580

The proxy and ProxyAdmin are precompiled so Optimism versions may be required.

Thanks so much for reporting it! The project owner will review and triage this issue as soon as they can.

**Comment by guanzhenxing** [comment]
Hi @abcoathup !

Thanks! Looking forward to it working on the Optimism network!

**Comment by abcoathup** [comment]
Also see forum question: https://forum.openzeppelin.com/t/openzeppelin-upgrades-support-for-optimism/5511.

**Comment by frangio** [comment]
We have some other things with more priority in the roadmap but it would be nice to support Optimism.

How does one detect that the current network is on Optimism? Is it a different chain id?

**Comment by guanzhenxing** [comment]
Hi @frangio .
The Optimism has different chain id. The Optimistic Ethereum (mainnet) is 10, and Optimistic Ethereum (Kovan) is 69

**Comment by frangio** [comment]
I'm going to assume the plugins will work as-is on [Optimism v2](https://community.optimism.io/docs/developers/l2/changeset.html). If someone runs into any problems please create a new issue.
