### ISSUE TITLE
"Bytecode is not a valid hex string" when updating hardhat-upgrades to 1.8 from 1.6

### ISSUE THREAD

**Issue by jacobrosenthal** [OpenZeppelin/openzeppelin-upgrades#359]
Were using sol7 in our contracts
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.7.6;
pragma experimental ABIEncoderV2;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";

contract Contract is ERC721Upgradeable {
```

in hardhat config
```
  solidity: {
    version: '0.7.6',
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
```

upgraded dependencies for latest hardhat-upgrades release 1.8:
```
    "@openzeppelin/contracts-upgradeable": "^3.4.1-solc-0.7-2",
    "@openzeppelin/hardhat-upgrades": "^1.8",
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "ethers": "^5.1.4",
    "hardhat": "^2.2.1",

```
But now deploy is failing out deploying the first proxy contract

```
Error: Bytecode is not a valid hex string
    at hashBytecode (/home/proj/node_modules/@openzeppelin/upgrades-core/src/version.ts:29:11)
    at Object.getVersion (/home/proj/node_modules/@openzeppelin/upgrades-core/src/version.ts:13:21)
    at Object.getUnlinkedBytecode (/home/proj/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:92:23)
    at Object.deployImpl (/home/proj/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:28:28)
    at Proxy.deployProxy (/home/proj/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:56:18)
    at SimpleTaskDefinition.deployTokens [as action] (/home/proj/eth/tasks/deploy-more.ts:90:28)
    at Environment._runTaskDefinition (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:130:14)
    at SimpleTaskDefinition.deploy (/home/proj/eth/tasks/deploy.ts:60:46)
    at Environment._runTaskDefinition (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
error Command failed with exit code 1.
```

Deploy of this contract is pretty standard, initialization done later
```
  const ConractFactory = await hre.ethers.getContractFactory('Contract');
  const contract = await hre.upgrades.deployProxy(ConractFactory, [], {
    initializer: false,
  });
  await contract.deployTransaction.wait();

```

Last known working versions were
```
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@openzeppelin/contracts-upgradeable": "^3.3.0",
    "@openzeppelin/hardhat-upgrades": "^1.6.0",
    "ethers": "^5.0.26",
    "hardhat": "^2.1.1",
```

**Comment by jacobrosenthal** [comment]
So I rolled all solidity contracts back to 7.2 and it seems to be working. Can you confirm current supported solc7 is 7.2? Also is that documented outside of the release tag presuming thats what this means? `3.4.1-solc-0.7-2` Ive searched the changelog and blog release any theyre not very specific on sol7 support

**Comment by frangio** [comment]
Let me take a look at this, all Solidity versions should be supported so this is a bug.

**Comment by frangio** [comment]
Would you mind sharing your artifact file found somewhere like `artifacts/contracts/Contract.sol/Contract.json`?

**Comment by jacobrosenthal** [comment]
Surely. Yeah thinking about it now, a different upgradable contract does deploy successfully before this one, so it cant be broken for all contracts and could be something in this one

```
0x608060405234801561001057600080fd5b506129d7806100206000396000f3fe608060405234801561001057600080fd5b50600436106101735760003560e01c80636352211e116100de578063991182da11610097578063c1a70e6c11610071578063c1a70e6c14610334578063c87b56dd14610347578063e6a9616b1461035a578063e985e9c51461036257610173565b8063991182da146102fb578063a22cb4651461030e578063b88d4fde1461032157610173565b80636352211e146102925780636c0360eb146102a557806370a08231146102ad5780638465ad44146102c0578063868e2810146102e057806395d89b41146102f357610173565b806323b872dd1161013057806323b872dd146102135780632f745c5914610226578063314d1ff71461023957806342842e0e14610259578063485cc9551461026c5780634f6ccce71461027f57610173565b806301ffc9a71461017857806306fdde03146101a1578063081812fc146101b6578063095ea7b3146101d657806318160ddd146101eb5780631f94f54014610200575b600080fd5b61018b6101863660046122d5565b610375565b6040516101989190612514565b60405180910390f35b6101a9610398565b604051610198919061251f565b6101c96101c436600461244d565b61042e565b60405161019891906124bc565b6101e96101e43660046122ac565b610490565b005b6101f3610566565b60405161019891906126fc565b61018b61020e36600461244d565b610577565b6101e9610221366004612196565b610588565b6101f36102343660046122ac565b6105df565b61024c61024736600461214a565b610608565b60405161019891906124d0565b6101e9610267366004612196565b610699565b6101e961027a366004612164565b6106b4565b6101f361028d36600461244d565b6107a9565b6101c96102a036600461244d565b6107b7565b6101a96107df565b6101f36102bb36600461214a565b610840565b6102d36102ce36600461244d565b6108a8565b6040516101989190612656565b6101e96102ee3660046122fd565b6109ac565b6101a9610b1d565b6101e9610309366004612465565b610b7e565b6101e961031c366004612283565b610bf0565b6101e961032f3660046121d1565b610cf5565b6102d36103423660046123b2565b610d53565b6101a961035536600461244d565b610f65565b6101e96111e6565b61018b610370366004612164565b611209565b6001600160e01b0319811660009081526033602052604090205460ff165b919050565b606a8054604080516020601f60026000196101006001881615020190951694909404938401819004810282018101909252828152606093909290918301828280156104245780601f106103f957610100808354040283529160200191610424565b820191906000526020600020905b81548152906001019060200180831161040757829003601f168201915b5050505050905090565b600061043982611237565b6104745760405162461bcd60e51b815260040180806020018281038252602c8152602001806128cc602c913960400191505060405180910390fd5b506000908152606860205260409020546001600160a01b031690565b600061049b826107b7565b9050806001600160a01b0316836001600160a01b031614156104ee5760405162461bcd60e51b81526004018080602001828103825260218152602001806129506021913960400191505060405180910390fd5b806001600160a01b0316610500611244565b6001600160a01b0316148061051c575061051c81610370611244565b6105575760405162461bcd60e51b81526004018080602001828103825260388152602001806127f16038913960400191505060405180910390fd5b6105618383611248565b505050565b600061057260666112b6565b905090565b600061058282611237565b92915050565b610599610593611244565b826112c1565b6105d45760405162461bcd60e51b81526004018080602001828103825260318152602001806129716031913960400191505060405180910390fd5b610561838383611365565b6001600160a01b038216600090815260656020526040812061060190836114b1565b9392505050565b6060600061061583610840565b905060008167ffffffffffffffff8111801561063057600080fd5b5060405190808252806020026020018201604052801561065a578160200160208202803683370190505b50905060005b828110156106915761067285826105df565b82828151811061067e57fe5b6020908102919091010152600101610660565b509392505050565b61056183838360405180602001604052806000815250610cf5565b600054610100900460ff16806106cd57506106cd6114bd565b806106db575060005460ff16155b6107165760405162461bcd60e51b815260040180806020018281038252602e81526020018061287c602e913960400191505060405180910390fd5b600054610100900460ff16158015610741576000805460ff1961ff0019909116610100171660011790555b609780546001600160a01b038086166001600160a01b03199283161790925560998054928516929091169190911790556040805160608101909152602380825261079391906127ce60208301396114ce565b8015610561576000805461ff0019169055505050565b6000806106916066846114e1565b60006105828260405180606001604052806029815260200161285360299139606691906114fd565b606d8054604080516020601f60026000196101006001881615020190951694909404938401819004810282018101909252828152606093909290918301828280156104245780601f106103f957610100808354040283529160200191610424565b60006001600160a01b0382166108875760405162461bcd60e51b815260040180806020018281038252602a815260200180612829602a913960400191505060405180910390fd5b6001600160a01b0382166000908152606560205260409020610582906112b6565b6108b0611fb1565b600082815260986020908152604091829020825161016081018452815460ff9081161515825260018301549382019390935260028201549381019390935260038101549091606084019116600581111561090657fe5b600581111561091157fe5b81526020016003820160019054906101000a900460ff16600a81111561093357fe5b600a81111561093e57fe5b81526004820154602082015260058201546001600160a01b0381166040830152606090910190600160a01b900460ff16600981111561097957fe5b600981111561098457fe5b8152600682015460208201526007820154604082015260089091015460609091015292915050565b6097546001600160a01b03163314806109cf57506099546001600160a01b031633145b6109f45760405162461bcd60e51b81526004016109eb90612572565b60405180910390fd5b610a018160200151611237565b610a1d5760405162461bcd60e51b81526004016109eb906125cf565b60208082018051600090815260989092526040918290208351815490151560ff199182161782559151600180830191909155928401516002820155606084015160038201805486959394929391921690836005811115610a7957fe5b0217905550608082015160038201805461ff00191661010083600a811115610a9d57fe5b021790555060a0820151600482015560c08201516005820180546001600160a01b0319166001600160a01b039092169190911780825560e0840151919060ff60a01b1916600160a01b836009811115610af257fe5b0217905550610100820151600682015561012082015160078201556101409091015160089091015550565b606b8054604080516020601f60026000196101006001881615020190951694909404938401819004810282018101909252828152606093909290918301828280156104245780601f106103f957610100808354040283529160200191610424565b6097546001600160a01b0316331480610ba157506099546001600160a01b031633145b610bbd5760405162461bcd60e51b81526004016109eb90612572565b6001600160a01b038116610bd957610bd48261150a565b610bec565b610bec610be5836107b7565b8284611365565b5050565b610bf8611244565b6001600160a01b0316826001600160a01b03161415610c5e576040805162461bcd60e51b815260206004820152601960248201527f4552433732313a20617070726f766520746f2063616c6c657200000000000000604482015290519081900360640190fd5b8060696000610c6b611244565b6001600160a01b03908116825260208083019390935260409182016000908120918716808252919093529120805460ff191692151592909217909155610caf611244565b6001600160a01b03167f17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c318360405180821515815260200191505060405180910390a35050565b610d06610d00611244565b836112c1565b610d415760405162461bcd60e51b81526004018080602001828103825260318152602001806129716031913960400191505060405180910390fd5b610d4d848484846115d7565b50505050565b610d5b611fb1565b6097546001600160a01b0316331480610d7e57506099546001600160a01b031633145b610d9a5760405162461bcd60e51b81526004016109eb90612572565b815160011115610dbc5760405162461bcd60e51b81526004016109eb9061261f565b610dce8260c001518360000151611629565b6000604051806101600160405280600115158152602001846000015181526020018460400151815260200184606001516005811115610e0957fe5b81526020018460800151600a811115610e1e57fe5b815260200142815260200184602001516001600160a01b031681526020018460a001516009811115610e4c57fe5b815260006020808301829052604080840183905260609384018390528751835260988252918290208451815490151560ff1991821617825591850151600180830191909155928501516002820155928401516003840180549596508695919390929190911690836005811115610ebe57fe5b0217905550608082015160038201805461ff00191661010083600a811115610ee257fe5b021790555060a0820151600482015560c08201516005820180546001600160a01b0319166001600160a01b039092169190911780825560e0840151919060ff60a01b1916600160a01b836009811115610f3757fe5b0217905550610100820151600682015561012082015160078201556101409091015160089091015592915050565b6060610f7082611237565b610fab5760405162461bcd60e51b815260040180806020018281038252602f815260200180612921602f913960400191505060405180910390fd5b6000828152606c602090815260408083208054825160026001831615610100026000190190921691909104601f81018590048502820185019093528281529290919083018282801561103e5780601f106110135761010080835404028352916020019161103e565b820191906000526020600020905b81548152906001019060200180831161102157829003601f168201915b50505050509050600061104f6107df565b905080516000141561106357509050610393565b8151156111245780826040516020018083805190602001908083835b6020831061109e5780518252601f19909201916020918201910161107f565b51815160209384036101000a600019018019909216911617905285519190930192850191508083835b602083106110e65780518252601f1990920191602091820191016110c7565b6001836020036101000a0380198251168184511680821785525050505050509050019250505060405160208183030381529060405292505050610393565b8061112e85611757565b6040516020018083805190602001908083835b602083106111605780518252601f199092019160209182019101611141565b51815160209384036101000a600019018019909216911617905285519190930192850191508083835b602083106111a85780518252601f199092019160209182019101611189565b6001836020036101000a0380198251168184511680821785525050505050509050019250505060405160208183030381529060405292505050919050565b6112076040518060600160405280602381526020016127ce602391396114ce565b565b6001600160a01b03918216600090815260696020908152604080832093909416825291909152205460ff1690565b6000610582606683611832565b3390565b600081815260686020526040902080546001600160a01b0319166001600160a01b038416908117909155819061127d826107b7565b6001600160a01b03167f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b92560405160405180910390a45050565b60006105828261183e565b60006112cc82611237565b6113075760405162461bcd60e51b815260040180806020018281038252602c8152602001806127a2602c913960400191505060405180910390fd5b6000611312836107b7565b9050806001600160a01b0316846001600160a01b0316148061134d5750836001600160a01b03166113428461042e565b6001600160a01b0316145b8061135d575061135d8185611209565b949350505050565b826001600160a01b0316611378826107b7565b6001600160a01b0316146113bd5760405162461bcd60e51b81526004018080602001828103825260298152602001806128f86029913960400191505060405180910390fd5b6001600160a01b0382166114025760405162461bcd60e51b815260040180806020018281038252602481526020018061277e6024913960400191505060405180910390fd5b61140d838383610561565b611418600082611248565b6001600160a01b038316600090815260656020526040902061143a9082611842565b506001600160a01b038216600090815260656020526040902061145d908261184e565b5061146a6066828461185a565b5080826001600160a01b0316846001600160a01b03167fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef60405160405180910390a4505050565b60006106018383611870565b60006114c8306118d4565b15905090565b8051610bec90606d90602084019061200e565b60008080806114f086866118da565b9097909650945050505050565b600061135d848484611955565b6000611515826107b7565b905061152381600084610561565b61152e600083611248565b6000828152606c6020526040902054600260001961010060018416150201909116041561156c576000828152606c6020526040812061156c9161209a565b6001600160a01b038116600090815260656020526040902061158e9083611842565b5061159a606683611a1f565b5060405182906000906001600160a01b038416907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef908390a45050565b6115e2848484611365565b6115ee84848484611a2b565b610d4d5760405162461bcd60e51b815260040180806020018281038252603281526020018061274c6032913960400191505060405180910390fd5b6001600160a01b038216611684576040805162461bcd60e51b815260206004820181905260248201527f4552433732313a206d696e7420746f20746865207a65726f2061646472657373604482015290519081900360640190fd5b61168d81611237565b156116df576040805162461bcd60e51b815260206004820152601c60248201527f4552433732313a20746f6b656e20616c7265616479206d696e74656400000000604482015290519081900360640190fd5b6116eb60008383610561565b6001600160a01b038216600090815260656020526040902061170d908261184e565b5061171a6066828461185a565b5060405181906001600160a01b038416906000907fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef908290a45050565b60608161177c57506040805180820190915260018152600360fc1b6020820152610393565b8160005b811561179457600101600a82049150611780565b60008167ffffffffffffffff811180156117ad57600080fd5b506040519080825280601f01601f1916602001820160405280156117d8576020820181803683370190505b50859350905060001982015b831561182957600a840660300160f81b8282806001900393508151811061180757fe5b60200101906001600160f81b031916908160001a905350600a840493506117e4565b50949350505050565b60006106018383611b93565b5490565b60006106018383611bab565b60006106018383611c71565b600061135d84846001600160a01b038516611cbb565b815460009082106118b25760405162461bcd60e51b815260040180806020018281038252602281526020018061272a6022913960400191505060405180910390fd5b8260000182815481106118c157fe5b9060005260206000200154905092915050565b3b151590565b81546000908190831061191e5760405162461bcd60e51b81526004018080602001828103825260228152602001806128aa6022913960400191505060405180910390fd5b600084600001848154811061192f57fe5b906000526020600020906002020190508060000154816001015492509250509250929050565b600082815260018401602052604081205482816119f05760405162461bcd60e51b81526004018080602001828103825283818151815260200191508051906020019080838360005b838110156119b557818101518382015260200161199d565b50505050905090810190601f1680156119e25780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b50846000016001820381548110611a0357fe5b9060005260206000209060020201600101549150509392505050565b60006106018383611d52565b6000611a3f846001600160a01b03166118d4565b611a4b5750600161135d565b6000611b59630a85bd0160e11b611a60611244565b88878760405160240180856001600160a01b03168152602001846001600160a01b0316815260200183815260200180602001828103825283818151815260200191508051906020019080838360005b83811015611ac7578181015183820152602001611aaf565b50505050905090810190601f168015611af45780820380516001836020036101000a031916815260200191505b5095505050505050604051602081830303815290604052906001600160e01b0319166020820180516001600160e01b03838183161783525050505060405180606001604052806032815260200161274c603291396001600160a01b0388169190611e26565b90506000818060200190516020811015611b7257600080fd5b50516001600160e01b031916630a85bd0160e11b1492505050949350505050565b60009081526001919091016020526040902054151590565b60008181526001830160205260408120548015611c675783546000198083019190810190600090879083908110611bde57fe5b9060005260206000200154905080876000018481548110611bfb57fe5b600091825260208083209091019290925582815260018981019092526040902090840190558654879080611c2b57fe5b60019003818190600052602060002001600090559055866001016000878152602001908152602001600020600090556001945050505050610582565b6000915050610582565b6000611c7d8383611b93565b611cb357508154600181810184556000848152602080822090930184905584548482528286019093526040902091909155610582565b506000610582565b600082815260018401602052604081205480611d20575050604080518082018252838152602080820184815286546001818101895560008981528481209551600290930290950191825591519082015586548684528188019092529290912055610601565b82856000016001830381548110611d3357fe5b9060005260206000209060020201600101819055506000915050610601565b60008181526001830160205260408120548015611c675783546000198083019190810190600090879083908110611d8557fe5b9060005260206000209060020201905080876000018481548110611da557fe5b600091825260208083208454600290930201918255600193840154918401919091558354825289830190526040902090840190558654879080611de457fe5b60008281526020808220600260001990940193840201828155600190810183905592909355888152898201909252604082209190915594506105829350505050565b606061135d848460008585611e3a856118d4565b611e8b576040805162461bcd60e51b815260206004820152601d60248201527f416464726573733a2063616c6c20746f206e6f6e2d636f6e7472616374000000604482015290519081900360640190fd5b600080866001600160a01b031685876040518082805190602001908083835b60208310611ec95780518252601f199092019160209182019101611eaa565b6001836020036101000a03801982511681845116808217855250505050505090500191505060006040518083038185875af1925050503d8060008114611f2b576040519150601f19603f3d011682016040523d82523d6000602084013e611f30565b606091505b5091509150611f40828286611f4b565b979650505050505050565b60608315611f5a575081610601565b825115611f6a5782518084602001fd5b60405162461bcd60e51b81526020600482018181528451602484015284518593919283926044019190850190808383600083156119b557818101518382015260200161199d565b60408051610160810182526000808252602082018190529181018290529060608201908152602001600081526000602082018190526040820181905260609091019081526020016000815260200160008152602001600081525090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282612044576000855561208a565b82601f1061205d57805160ff191683800117855561208a565b8280016001018555821561208a579182015b8281111561208a57825182559160200191906001019061206f565b506120969291506120e1565b5090565b50805460018160011615610100020316600290046000825580601f106120c057506120de565b601f0160209004906000526020600020908101906120de91906120e1565b50565b5b8082111561209657600081556001016120e2565b80356001600160a01b038116811461039357600080fd5b8035801515811461039357600080fd5b80356006811061039357600080fd5b8035600a811061039357600080fd5b8035600b811061039357600080fd5b60006020828403121561215b578081fd5b610601826120f6565b60008060408385031215612176578081fd5b61217f836120f6565b915061218d602084016120f6565b90509250929050565b6000806000606084860312156121aa578081fd5b6121b3846120f6565b92506121c1602085016120f6565b9150604084013590509250925092565b600080600080608085870312156121e6578081fd5b6121ef856120f6565b935060206121fe8187016120f6565b935060408601359250606086013567ffffffffffffffff80821115612221578384fd5b818801915088601f830112612234578384fd5b81358181111561224057fe5b612252601f8201601f19168501612705565b91508082528984828501011115612267578485fd5b8084840185840137810190920192909252939692955090935050565b60008060408385031215612295578182fd5b61229e836120f6565b915061218d6020840161210d565b600080604083850312156122be578182fd5b6122c7836120f6565b946020939093013593505050565b6000602082840312156122e6578081fd5b81356001600160e01b031981168114610601578182fd5b6000610160808385031215612310578182fd5b61231981612705565b90506123248361210d565b815260208301356020820152604083013560408201526123466060840161211d565b60608201526123576080840161213b565b608082015260a083013560a082015261237260c084016120f6565b60c082015261238360e0840161212c565b60e082015261010083810135908201526101208084013590820152610140928301359281019290925250919050565b600060e082840312156123c3578081fd5b60405160e0810181811067ffffffffffffffff821117156123e057fe5b604052823581526123f3602084016120f6565b60208201526040830135604082015261240e6060840161211d565b606082015261241f6080840161213b565b608082015261243060a0840161212c565b60a082015261244160c084016120f6565b60c08201529392505050565b60006020828403121561245e578081fd5b5035919050565b60008060408385031215612477578182fd5b8235915061218d602084016120f6565b6001600160a01b03169052565b15159052565b600681106124a457fe5b9052565b600a81106124a457fe5b600b81106124a457fe5b6001600160a01b0391909116815260200190565b6020808252825182820181905260009190848201906040850190845b81811015612508578351835292840192918401916001016124ec565b50909695505050505050565b901515815260200190565b6000602080835283518082850152825b8181101561254b5785810183015185820160400152820161252f565b8181111561255c5783604083870101525b50601f01601f1916929092016040019392505050565b6020808252603b908201527f4f6e6c792074686520436f7265206f722041646d696e2061646472657373657360408201527f2063616e20666964646c652077697468206172746966616374732e0000000000606082015260800190565b60208082526030908201527f796f752063616e6e6f742075706461746520616e20617274696661637420746860408201526f185d08191bd95cdb89dd08195e1a5cdd60821b606082015260800190565b6020808252601c908201527f6172746966616374206964206d75737420626520706f73697469766500000000604082015260600190565b60006101608201905061266a828451612494565b60208301516020830152604083015160408301526060830151612690606084018261249a565b5060808301516126a360808401826124b2565b5060a083015160a083015260c08301516126c060c0840182612487565b5060e08301516126d360e08401826124a8565b506101008381015190830152610120808401519083015261014092830151929091019190915290565b90815260200190565b60405181810167ffffffffffffffff8111828210171561272157fe5b60405291905056fe456e756d657261626c655365743a20696e646578206f7574206f6620626f756e64734552433732313a207472616e7366657220746f206e6f6e20455243373231526563656976657220696d706c656d656e7465724552433732313a207472616e7366657220746f20746865207a65726f20616464726573734552433732313a206f70657261746f7220717565727920666f72206e6f6e6578697374656e7420746f6b656e68747470733a2f2f7a6b67612e6d652f746f6b656e2d7572692f61727469666163742f4552433732313a20617070726f76652063616c6c6572206973206e6f74206f776e6572206e6f7220617070726f76656420666f7220616c6c4552433732313a2062616c616e636520717565727920666f7220746865207a65726f20616464726573734552433732313a206f776e657220717565727920666f72206e6f6e6578697374656e7420746f6b656e496e697469616c697a61626c653a20636f6e747261637420697320616c726561647920696e697469616c697a6564456e756d657261626c654d61703a20696e646578206f7574206f6620626f756e64734552433732313a20617070726f76656420717565727920666f72206e6f6e6578697374656e7420746f6b656e4552433732313a207472616e73666572206f6620746f6b656e2074686174206973206e6f74206f776e4552433732314d657461646174613a2055524920717565727920666f72206e6f6e6578697374656e7420746f6b656e4552433732313a20617070726f76616c20746f2063757272656e74206f776e65724552433732313a207472616e736665722063616c6c6572206973206e6f74206f776e6572206e6f7220617070726f766564a2646970667358221220f9ce366e3e181115aa0096c579c041c82a200bd7e4e27ba7e463599b9f7f3c0a64736f6c63430007060033
```

**Comment by frangio** [comment]
Are you using external library linking in any of your contracts? I'm struggling to reproduce the error so if you could try to put together a minimal repository that reproduces it I would appreciate it.

**Comment by jacobrosenthal** [comment]
Yes theres several contracts that use external linking, however theyre farther along in the deploy process and this one that keeps failing is not, as you can see above. Well probably just not update before our next release at which point everything will be open sourced and should be easier to discuss.

**Comment by frangio** [comment]
From looking at the code it makes sense that other unrelated contracts would also be causing this. I'll try to reproduce it with this inof now!

**Comment by jacobrosenthal** [comment]
Id be more than happy to share more. Can we chat in telegram @jacobrosenthal or discord Jacob Rosenthal#3661

**Comment by frangio** [comment]
This should be fixed on the latest release of `@openzeppelin/upgrades-core`.
