### ISSUE TITLE
deployProxy "Cannot read property 'wait' of null"

### ISSUE THREAD

**Issue by jacobrosenthal** [OpenZeppelin/openzeppelin-upgrades#360]
Probably very similar to https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/354

During high transaction periods, deployProxy returns null. presumably the internal proxy deploy transaction isnt being waited on, and or one of the two tx is failing silently

```
An unexpected error occurred:

TypeError: Cannot read property 'wait' of null
    at SimpleTaskDefinition.deployWhitelist [as action] (/home/proj/eth/tasks/deploy-more.ts:64:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Environment._runTaskDefinition (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.deploy (/home/proj/eth/tasks/deploy.ts:51:32)
    at Environment._runTaskDefinition (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at main (/home/proj/node_modules/hardhat/src/internal/cli/cli.ts:188:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /home/jacob/.nvm/versions/node/v14.15.4/bin/node
Arguments: /home/proj/.yarn/releases/yarn-1.22.10.cjs hardhat:prod deploy --verbose
Directory: /home/proj/eth
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

during normal network conditions, the code obviously works fine and deployTransaction exists and is waited on successfully
```
  const WhitelistFactory = await hre.ethers.getContractFactory('Whitelist');
  const whitelist = await hre.upgrades.deployProxy(WhitelistFactory, [
    args.controllerWalletAddress,
    args.whitelistEnabled,
  ]);
  await whitelist.deployTransaction.wait();
```

**Comment by frangio** [comment]
I published a new release of the Hardhat plugin that I think should fix this.
