### ISSUE TITLE
Mapping with enum

### ISSUE THREAD

**Issue by Nenad7955** [OpenZeppelin/openzeppelin-upgrades#361]
Hey guys! 
enum Option...
mapping(Option => uint)...
causes this error:

     Error: An unexpected condition occurred. Please report this at https://zpl.in/upgrades/report
      at Object.assert (node_modules/@openzeppelin/upgrades-core/src/utils/assert.ts:8:11)
      at StorageLayoutComparator.uncachedGetTypeChange (node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:189:9)
      at StorageLayoutComparator.getTypeChange (node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:110:27)
      at StorageLayoutComparator.getFieldChange (node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:82:29)
      at levenshtein_1.levenshtein (node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:71:63)
      at change (node_modules/@openzeppelin/upgrades-core/src/levenshtein.ts:77:20)
      at buildMatrix (node_modules/@openzeppelin/upgrades-core/src/levenshtein.ts:46:29)
      at Object.levenshtein (node_modules/@openzeppelin/upgrades-core/src/levenshtein.ts:16:18)
      at StorageLayoutComparator.layoutLevenshtein (node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:71:17)
      at StorageLayoutComparator.compareLayouts (node_modules/@openzeppelin/upgrades-core/src/storage/compare.ts:63:47)

**Comment by frangio** [comment]
Hi @Nenad7955. Can you please share the source code for the current version and the one you're trying to upgrade to?

**Comment by Nenad7955** [comment]
i just added a setter for a variable, source code ill be able to share in a few hours. 
versions:
"@openzeppelin/contracts-upgradeable": "^4.1.0",
"@openzeppelin/hardhat-upgrades": "^1.7.0",
In any case, as soon as I commented out the mapping with the enum as key, the error dissapeared.

**Comment by frangio** [comment]
I've fixed this in https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/75e9a407c3a38535b728ec1027fed721b89bf179, in the sense that it's no longer an unexpected condition. But upgrading a mapping key from uint to enum is considered a bad upgrade and not allowed.
