### ISSUE TITLE
truffle: Web3ProviderEngine does not support synchronous requests

### ISSUE THREAD

**Issue by wozz** [OpenZeppelin/openzeppelin-upgrades#378]
While trying to deploy upgradeable contracts using a ledger for signing, I encountered this error:
```
MIGRATION_STATUS:{"status":"postAllMigrations","data":{"dryRun":false,"error":"Error: Web3ProviderEngine does not support synchronous requests."}}
Error: Web3ProviderEngine does not support synchronous requests.
    at Web3ProviderEngine.send (/project/node_modules/web3-provider-engine/index.js:114:9)
    at Web3ProviderEngine.send (/project/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:101:1)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at bound  (internal/util.js:296:12)
    at Object.send (/project/node_modules/@openzeppelin/truffle-upgrades/src/utils/wrap-provider.ts:14:39)
    at Object.getChainId (/project/node_modules/@openzeppelin/upgrades-core/src/provider.ts:22:29)
    at Function.forNetwork (/project/node_modules/@openzeppelin/upgrades-core/src/manifest.ts:46:31)
    at deployProxy (/project/node_modules/@openzeppelin/truffle-upgrades/src/deploy-proxy.ts:35:35)
    at module.exports (/project/migrations/2_deploy_upgradeable_contract.js:8:26)
```

Seems to be a similar issue to described here (and my setup is very similar to that issue): https://github.com/LedgerHQ/ledgerjs/issues/508

**Comment by Amxx** [comment]
Hello @wozz 

This appears to be a Web3ProviderEngine / Ledger issue and doesn't originate from OZ's upgrades plugins. You might what to raise an issue in the corresponding repo.

**Comment by frangio** [comment]
I think this is actually an issue in this project because we're calling `send` if it's available instead of `sendAsync`. This should've been fixed in #341 but it appears it wasn't implemented correctly.

**Comment by frangio** [comment]
Should be fixed now in the latest release (`@openzeppelin/truffle-upgrades@1.7.1`).

@wozz Please try it out and let us know if it works.

**Comment by wozz** [comment]
Thanks! I will test this evening.
