### ISSUE TITLE
TypeError: Cannot read property 'errors' of undefined

### ISSUE THREAD

**Issue by zhangliang7190** [OpenZeppelin/openzeppelin-upgrades#381]
I have used the @openzeppelin/truffle-upgrades@1.5.0 without the package @openzeppelin/upgrades-core when I deploy an upgradable contract some weeks ago。I create a new project with my contracts code and take this errors：

```
TypeError: Cannot read property 'errors' of undefined
    at /Users/work/allan/node_modules/@openzeppelin/truffle-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:109:58
    at Array.map (<anonymous>)
    at getErrors (/Users/work/allan/node_modules/@openzeppelin/truffle-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:109:26)
    at Object.assertUpgradeSafe (/Users/work/allan/node_modules/@openzeppelin/truffle-upgrades/node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:13:16)
    at deployProxy (/Users/work/allan/node_modules/@openzeppelin/truffle-upgrades/src/deploy-proxy.ts:49:3)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at module.exports (/Users/work/allan/migrations/10_mdxpool_deploy.js:8:24)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:80:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:218:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:253:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:147:1)
```

I have change all the packets to the same version with my old project ,but still occured the same error?
how Can I do not use this @openzeppelin/upgrades-core packages? OR fix this errors?
Thank you

**Comment by zhangliang7190** [comment]
my system options : 
Truffle v5.3.8 (core: 5.3.8)
Solidity - 0.6.12 (solc-js)
Node v15.9.0
Web3.js v1.3.6

**Comment by zhangliang7190** [comment]
runable truffle packages:
```json
{
  "name": "[hardhat-project](https://npmjs.com/package/hardhat-project)",
  "devDependencies": {
    "[@nomiclabs/hardhat-ethers](https://npmjs.com/package/@nomiclabs/hardhat-ethers)": "^2.0.1",
    "[@nomiclabs/hardhat-waffle](https://npmjs.com/package/@nomiclabs/hardhat-waffle)": "^2.0.1",
    "[@openzeppelin/hardhat-upgrades](https://npmjs.com/package/@openzeppelin/hardhat-upgrades)": "^1.6.0",
    "[@openzeppelin/truffle-upgrades](https://npmjs.com/package/@openzeppelin/truffle-upgrades)": "^1.5.0",
    "[chai](https://npmjs.com/package/chai)": "^4.3.0",
    "[ethereum-waffle](https://npmjs.com/package/ethereum-waffle)": "^3.2.2",
    "[ethers](https://npmjs.com/package/ethers)": "^5.0.31",
    "[hardhat](https://npmjs.com/package/hardhat)": "^2.0.10"
  },
  "dependencies": {
    "[@openzeppelin/contracts](https://npmjs.com/package/@openzeppelin/contracts)": "^3.4.0",
    "[@openzeppelin/contracts-upgradeable](https://npmjs.com/package/@openzeppelin/contracts-upgradeable)": "^3.4.0",
    "[@openzeppelin/upgrades-core](https://npmjs.com/package/@openzeppelin/upgrades-core)": "^1.5.0",
    "[@pancakeswap/pancake-swap-lib](https://npmjs.com/package/@pancakeswap/pancake-swap-lib)": "^0.0.4",
    "[@truffle/hdwallet-provider](https://npmjs.com/package/@truffle/hdwallet-provider)": "^1.4.0",
    "[truffle-hdwallet-provider](https://npmjs.com/package/truffle-hdwallet-provider)": "^1.0.17"
  }
}
```

**Comment by Amxx** [comment]
Hello @zhangliang7190 

`@openzeppelin/upgrades-core` is an internal "library" that is used by `@openzeppelin/truffle-upgrades` and `@openzeppelin/hardhat-upgrades`. You should not have to deal with it directly.

Can you share the line of script that, when called, triggers this error ?

**Comment by Amxx** [comment]
Note that you are not using the latest version of the upgrades plugin. Version are backward compatible, and include a manifest migration mechanism.

I would encourage you to save a backup of your `.openzeppelin` folder, upgrade to the latest version of the plugin (`@openzeppelin/truffle-upgrades:1.7.0`) and see it that fixes anything.

**Comment by zhangliang7190** [comment]
> Note that you are not using the latest version of the upgrades plugin. Version are backward compatible, and include a manifest migration mechanism.
> 
> I would encourage you to save a backup of your `.openzeppelin` folder, upgrade to the latest version of the plugin (`@openzeppelin/truffle-upgrades:1.7.0`) and see it that fixes anything.

I think that is my contracts's problem. I have to try it. tks
