### ISSUE TITLE
Support user defined value types.

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-upgrades#477]
When using user defined value types (available since 0.8.8) the ast-dereferencer fails.

```
Compiling 111 files with 0.8.10
An unexpected error occurred:

Error: No node with id 25034 of type StructDefinition,EnumDefinition
    at deref (projectRoot/node_modules/@openzeppelin/upgrades-core/src/ast-dereferencer.ts:38:11)
    at projectRoot/node_modules/@openzeppelin/upgrades-core/src/utils/curry.ts:11:19
    at extractStorageLayout (projectRoot/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:59:29)
    at validate (projectRoot/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:165:67)
    at OverriddenTaskDefinition._action (projectRoot/node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:62:25)
    at Environment._runTaskDefinition (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (projectRoot/node_modules/hardhat/src/builtin-tasks/compile.ts:975:37)
    at Environment._runTaskDefinition (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (projectRoot/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
error Command failed with exit code 1.
```

Apparently, using [this contract](https://github.com/Amxx/openzeppelin-contracts/blob/breaking/Timers/udvt/contracts/utils/Timers.sol) replicated the issue.

Simple contract to reproduce the current error and test support:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

contract UserDefinedValueType {
    type Timestamp is uint64;
}
```

Note: As mentioned in https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/438 we need to be careful with Solidity 0.8.8 because it has buggy storage layout rules, they were fixed in 0.8.9. We should probably reject 0.8.8.

**Comment by frangio** [comment]
Related to https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/438, we should implement both at the same time.

**Comment by bbonanno** [comment]
Hi guys, any idea when will this be fixed?

**Comment by executionreverted** [comment]
No node with id 222 of type StructDefinition,EnumDefinition.


when defining custom type like:

type X is uint256;

**Comment by KholdStare** [comment]
Running into this issue. Can someone please provide an update? It's been almost a year!

**Comment by KholdStare** [comment]
@Amxx @frangio Hi, this is a show-stopper for us. I'm surprised user defined value types are unsupported - they've been around for quite a while. Any pointers on what the fix should be? My team and I would be happy to contribute

**Comment by frangio** [comment]
@KholdStare I've opened a pull request (https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/658). Please allow a bit of time for review.

Can you confirm if you are using Hardhat or Truffle plugins?

**Comment by KholdStare** [comment]
@frangio I was using the hardhat plugin. Thank you for the quick turnaround time. I'll take a look at the PR too.

**Comment by frangio** [comment]
@KholdStare This was published in the latest releases.
