### ISSUE TITLE
Defender `proposeUpgrade` method fails in this scenario.

### ISSUE THREAD

**Issue by DsAtHuH** [OpenZeppelin/openzeppelin-upgrades#548]
When running `yarn deploy rinkeby` on the [branch defender of this project](https://github.com/HUH-Token/huh-governance/tree/6728f1067a2641fc7df6ef09ae457b2758643565), defender fails to propose the upgrade at [line 17 of the upgrade script](https://github.com/HUH-Token/huh-governance/blob/6728f1067a2641fc7df6ef09ae457b2758643565/src/upgrade.js#L17) resulting in the following error:

```bash
❯ yarn deploy rinkeby
yarn run v1.22.17
$ yarn hardhat deploy --network rinkeby
$ node --require esm node_modules/.bin/hardhat deploy --network rinkeby
Nothing to compile
deploying "ERC20Mock" (tx: 0xac95267815d45f8842a5309965d37ec6db3f6925361673c31411918647159f82)...: deployed at 0xc8EF7026CfF4765f797543330681aB1eB5D97805 with 648507 gas
deploying "Timestamp" (tx: 0x913b47ba4421abec12eedc615905943cdb91c42b7ccb2ac3574a015511001efc)...: deployed at 0x347897a7C3963CF6d05ddb9e8Fe037ea4D081c28 with 127633 gas
deploying "HUHGovernance_Implementation" (tx: 0xa859fc45365048408696340faa77c100f01c584329900f21c8117ca44bebbac4)...: deployed at 0xc9428ea129EE105a137ADD6C19EE4611a00C9eaE with 2795949 gas
deploying "HUHGovernance_Proxy" (tx: 0xb98eba87ef5e10185e66353ea7de482d9151c0c97fa8ab4c3c34c5289f7c5517)...: deployed at 0x8e626F68B07b9CC68654e92d0C8e5BcC4210b1d9 with 393857 gas
Transferring ownership of ProxyAdmin...
Transferred ownership of ProxyAdmin to: 0x9f01873CE9eD346b2ae76eb36dD98ff0198DF9aA
Preparing proposal...
An unexpected error occurred:

Error: ERROR processing /home/dsathuh/Workspaces/HUH/huh-governance/deploy/03-upgrade-huh-governance.js:
Error: types/values length mismatch (count={"types":3,"values":0}, value={"types":[{"name":"_huhToken","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true},{"name":"_timestamp","type":"address","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"address","_isParamType":true},{"name":"maximumLockTimeInYears","type":"uint256","indexed":null,"components":null,"arrayLength":null,"arrayChildren":null,"baseType":"uint256","_isParamType":true}],"values":[]}, code=INVALID_ARGUMENT, version=abi/5.5.0)
    at Logger.makeError (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at AbiCoder.encode (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@ethersproject/abi/src.ts/abi-coder.ts:102:20)
    at Interface._encodeParams (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@ethersproject/abi/src.ts/interface.ts:325:31)
    at Interface.encodeDeploy (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@ethersproject/abi/src.ts/interface.ts:329:21)
    at getDeployData (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:53:45)
    at deployProxyImpl (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:66:22)
    at Proxy.prepareUpgrade (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/prepare-upgrade.ts:25:22)
    at Proxy.proposeUpgrade (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/src/propose-upgrade.ts:53:31)
    at upgrade (/home/dsathuh/Workspaces/HUH/huh-governance/src/upgrade.js:17:22)
    at DeploymentsManager.executeDeployScripts (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at DeploymentsManager.runDeploy (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:568:32)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:653:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by DsAtHuH** [comment]
Thank you for your feedback @ericglau. I implemented the necessary changes to pass upgradeability safe check in the [defender branch](https://github.com/HUH-Token/huh-governance/tree/1e7ea7beefe27e330ae76f45ad1886f9ca6cb791). Now when I run `yarn deploy rinkeby` the following error is being raised:

```bash
❯ yarn deploy rinkeby
yarn run v1.22.17
$ yarn hardhat deploy --network rinkeby
$ node --require esm node_modules/.bin/hardhat deploy --network rinkeby
Nothing to compile
deploying "ERC20Mock" (tx: 0x8cd864d49c744c28f1a7924ee7713ff7d851c75358dbcb14583873e6b4c60f0d)...: deployed at 0x4172a0BF02DE6D433E0301F3dEdC651F6A629440 with 648507 gas
deploying "Timestamp" (tx: 0xf4b573d1e5a8e2b7c71ab31562d24e3abb453739722658c06a895e4221ffeba7)...: deployed at 0xaDcDaA357cb76B947995e09511f63fD75b420E9c with 127633 gas
deploying "HUHGovernance_Implementation" (tx: 0x1fd7bdb16b32c3908be792fdce6ffd7925adfb5415176066fb501cc0aca5a18e)...: deployed at 0x1324527c5A035B1e504E967C353CAF8d70039b36 with 2795949 gas
deploying "HUHGovernance_Proxy" (tx: 0x84f31e42287ea4c7cdc9665b0191fde546af2e0c42f5acea6f068b162a6e6230)...: deployed at 0xF9F2508AFBD1dd88501D39ca0dEE19443129aCa0 with 393857 gas
Transferring ownership of ProxyAdmin...
Transferred ownership of ProxyAdmin to: 0x9f01873CE9eD346b2ae76eb36dD98ff0198DF9aA
Preparing proposal...
An unexpected error occurred:

Error: ERROR processing /home/dsathuh/Workspaces/HUH/huh-governance/deploy/03-upgrade-huh-governance.js:
Error: Deployment at address 0x1324527c5A035B1e504E967C353CAF8d70039b36 is not registered

To register a previously deployed proxy for upgrading, use the forceImport function.
    at getStorageLayoutForAddress (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/upgrades-core/src/manifest-storage-layout.ts:20:11)
    at deployImpl (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:108:27)
    at Proxy.prepareUpgrade (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/prepare-upgrade.ts:25:22)
    at Proxy.proposeUpgrade (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/src/propose-upgrade.ts:53:31)
    at upgrade (/home/dsathuh/Workspaces/HUH/huh-governance/src/upgrade.js:22:22)
    at Object.func (/home/dsathuh/Workspaces/HUH/huh-governance/deploy/03-upgrade-huh-governance.js:12:3)
    at DeploymentsManager.executeDeployScripts (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)
    at DeploymentsManager.runDeploy (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at DeploymentsManager.executeDeployScripts (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at DeploymentsManager.runDeploy (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:568:32)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:653:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

The error suggests:

> To register a previously deployed proxy for upgrading, use the forceImport function.

I was looking for examples on how to implement the forceImport call, but wasn't able to find still...

**Comment by DsAtHuH** [comment]
Thank you for your feedback @ericglau. In addition to the upgradeability safety check it looks like I also have to use [force import method](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#force-import) to make sure the proxy is registered before proposing an upgrade. This step is needed because the proxy was deployed by hardhat-deploy instead of OZ upgrades.

**Comment by DsAtHuH** [comment]
I implemented the changes with force import in [this commit](https://github.com/HUH-Token/huh-governance/tree/84c21392b3169623291851fe87e1f3f766976e80) at [line 22 of the file upgrade.js](https://github.com/HUH-Token/huh-governance/blob/defender/src/upgrade.js#L22). When the `proposeUpgrade` method is ran at [line 26 of the upgrade file](https://github.com/HUH-Token/huh-governance/blob/defender/src/upgrade.js#L26) the following error is raised:

```bash
❯ yarn deploy rinkeby
yarn run v1.22.17
$ yarn hardhat deploy --network rinkeby
$ node --require esm node_modules/.bin/hardhat deploy --network rinkeby
Nothing to compile
reusing "ERC20Mock" at 0x314Db4c5339870865b315A95FA6186F8Ed418F4A
reusing "Timestamp" at 0xfB89f9651eE121F37BB65A93a5e7B6DFFf19863F
deploying "HUHGovernance_Implementation" (tx: 0x9e5eebb9ee5eed71ace1af2ec131203dfcb8e08268ac3e6434cc034d2c49e2ef)...: deployed at 0xe15124c95044b9B16727341aEEd39d16899913e9 with 2795949 gas
deploying "HUHGovernance_Proxy" (tx: 0x85158262b8ed01c39896a828ff92e095322300a417a102ebb4db2e8ac616b2d7)...: deployed at 0x96b0dD04D41C6fEe6658a05aeb77115459604F3d with 393857 gas
Registering proxy for upgrade...
Proxy registered at: 0x96b0dD04D41C6fEe6658a05aeb77115459604F3d
Preparing proposal...
An unexpected error occurred:

Error: ERROR processing /home/dsathuh/Workspaces/HUH/huh-governance/deploy/03-upgrade-huh-governance.js:
Error: Requested an upgrade of kind uups but proxy is transparent
    at setProxyKind (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/upgrades-core/src/proxy-kind.ts:27:11)
    at processProxyKind (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/upgrades-core/src/proxy-kind.ts:54:5)
    at deployProxyImpl (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:68:3)
    at Proxy.prepareUpgrade (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/node_modules/@openzeppelin/hardhat-upgrades/src/prepare-upgrade.ts:25:22)
    at Proxy.proposeUpgrade (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/@openzeppelin/hardhat-defender/src/propose-upgrade.ts:53:31)
    at upgrade (/home/dsathuh/Workspaces/HUH/huh-governance/src/upgrade.js:26:22)
    at Object.func (/home/dsathuh/Workspaces/HUH/huh-governance/deploy/03-upgrade-huh-governance.js:10:3)
    at DeploymentsManager.executeDeployScripts (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)
    at DeploymentsManager.runDeploy (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:422:5)
    at DeploymentsManager.executeDeployScripts (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at DeploymentsManager.runDeploy (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:422:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:568:32)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat-deploy/src/index.ts:653:5)
    at Environment._runTaskDefinition (/home/dsathuh/Workspaces/HUH/huh-governance/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The error suggests the proxy kind is transparent but it was supposed to actually be UUPS as it was deployed by hardhat-deploy at line 11 of [the file 02-deploy-huh-governance.js](https://github.com/HUH-Token/huh-governance/blob/defender/deploy/02-deploy-huh-governance.js#L11).

**Comment by ericglau** [comment]
Looks like hardhat-deploy sets a proxy admin for UUPS, so the upgrades plugin incorrectly imports it as transparent.  We should fix the upgrades plugin to support importing this as UUPS.

**Comment by ericglau** [comment]
@DsAtHuH I also noticed that your [script](https://github.com/HUH-Token/huh-governance/blob/defender/src/upgrade.js#L19) is passing `constructorArgs` to `forceImport`.  Note that this isn't necessary for this function, since `forceImport` does not deploy the contract but only imports it.

To clarify my [comment above](https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/548#issuecomment-1077903350), constructors are not applicable for upgradeable contracts because the constructors would only initialize the storage at the implementation address (which is not used by the proxy) -- initializers should be used instead to initialize the storage at the proxy (see https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializers and https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies#the-constructor-caveat).  

It looks like some of your contracts have both an initializer and a constructor (which just calls the initializer).  From first glance, it appears to me that those constructors aren't necessary if you will only be using these contracts through proxies.

**Comment by DsAtHuH** [comment]
@ericglau , I appreciate your feedback on this matter.
From what I understood in my research, the constructor needs to be present at the moment in the contracts to attend a current requirement of hardhat-deploy.

**Comment by ericglau** [comment]
Fixed https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/548#issuecomment-1079080426 by https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/550, available in the latest release.
