### ISSUE TITLE
Reuse Truffle and Ethers tx waiting implementations or parameters

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#55]
In https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/47 I introduced `waitAndValidateDeployment` to wait until a tx is mined.

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/b3ae02961a87b990a30f7f4bc9d91668220ff00e/packages/core/src/deployment.ts#L33

There's at least two parameters here that te user might want to configure: the polling interval and the timeout. Libraries like Web3, Truffle, and Ethers already allow the user to configure these parameters and we should try to reuse them. We can also evaluate reusing their implementations for waiting a tx instead of rolling our own.

**Comment by jacobrosenthal** [comment]
Did this get snuck in somewhere else by any chance? With congestion what it is, and several other fixes, Im now not crashing and able to wait for deploys, but now I'm timing out :)

**Comment by frangio** [comment]
Can you clarify if you're running into an internal timeout of the plugin, or is it timing out when you use `.wait()`?

**Comment by jacobrosenthal** [comment]
looks internal
```
An unexpected error occurred:

TransactionMinedTimeout [Error]: Timed out waiting for transaction 0x5581653fa28a6d8a185d20cfa81a81b22e7af685543098070593109dc1010f78
    at Object.waitAndValidateDeployment (/home/proj/node_modules/@openzeppelin/upgrades-core/src/deployment.ts:62:15)
    at fetchOrDeployGeneric (/home/proj/node_modules/@openzeppelin/upgrades-core/src/impl-store.ts:42:5)
    at Object.deployImpl (/home/proj/eth/node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:40:10)
    at Proxy.deployProxy (/home/proj/eth/node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:56:18)
    at SimpleTaskDefinition.deployCore [as action] (/home/proj/eth/tasks/deploy-more.ts:171:26)
    at Environment._runTaskDefinition (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.deploy (/home/proj/eth/tasks/deploy.ts:67:54)
    at Environment._runTaskDefinition (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/home/proj/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14) {

```

**Comment by frangio** [comment]
As a workaround, anyone running into this can catch the `TransactionMinedTimeout` error and rerun `deployProxy`/`upgradeProxy`, which will resume waiting for the transaction that timed out.

**Comment by ericglau** [comment]
For Hardhat, the timeout and polling parameters are now configurable in the [latest release of the Hardhat Upgrades plugin](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%401.14.0) by using the `timeout` and `pollingInterval` options.  For more details, see [Common Options](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#common-options).

For Truffle, use Truffle's [network options for timeout and polling](https://trufflesuite.com/docs/truffle/reference/configuration.html#networks).
