### ISSUE TITLE
Can't compile after upgrading to latest version

### ISSUE THREAD

**Issue by Mrsblink** [OpenZeppelin/openzeppelin-upgrades#678]
So I was using this config to normally do upgrades to my proxy's.
```
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-etherscan": "^2.1.4",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@openzeppelin/contracts-upgradeable": "^4.2.0",
    "@openzeppelin/hardhat-upgrades": "^1.9.0",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.4.1",
    "hardhat": "^2.4.3"
  },
```

Then I upgraded everything to the latest version and now I'm unable to compile anymore.

```
TypeError: Cannot use 'in' operator to search for 'SourceUnit' in undefined
    at getNextProps (/home/mrsblink/PhpstormProjects/xxx/node_modules/solidity-ast/utils.js:40:27)
    at findAll (/home/mrsblink/PhpstormProjects/xxx/node_modules/solidity-ast/utils.js:20:22)
    at findAll.next (<anonymous>)
    at deref (/home/mrsblink/PhpstormProjects/xxx/node_modules/@openzeppelin/upgrades-core/src/ast-dereferencer.ts:30:18)
    at /home/mrsblink/PhpstormProjects/xxx/node_modules/@openzeppelin/upgrades-core/src/utils/curry.ts:11:19
    at loadLayoutType (/home/mrsblink/PhpstormProjects/xxx/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:137:23)
    at extractStorageLayout (/home/mrsblink/PhpstormProjects/xxx/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:69:11)
    at validate (/home/mrsblink/PhpstormProjects/xxx/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:167:67)
    at OverriddenTaskDefinition._action (/home/mrsblink/PhpstormProjects/xxx/node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:82:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Now when I reverted everything, I'm still not able to compile.
I really hope this hasn't locked my out of doing upgrades on a specific contract...

**Comment by ericglau** [comment]
I tried the devDependencies that you listed, and was able to compile.  Can you try deleting the `node_modules` folder, backup and delete the `package-lock.json` or `yarn.lock` file, and then do `npm install` or `yarn install` again?

**Comment by frangio** [comment]
@Mrsblink Can you confirm if this issue still occurs?

**Comment by clemsos** [comment]
I am having the same issue after doing the following [package upgrades](https://github.com/unlock-protocol/unlock/pull/10204)

```
@openzeppelin/contracts   4.7.3 -> 4.8.0
@openzeppelin/contracts-upgradeable 	4.7.3 -> 4.8.0
@openzeppelin/hardhat-upgrades 	1.16.1 -> 1.21.0
@openzeppelin/upgrades-core  1.12.0 -> 1.20.4
```

the error here

```
TypeError: Cannot use 'in' operator to search for 'SourceUnit' in undefined
    at getNextProps (/Users/clement/Dev/unlock/unlock/node_modules/solidity-ast/utils.js:40:27)
    at findAll (/Users/clement/Dev/unlock/unlock/node_modules/solidity-ast/utils.js:20:22)
    at findAll.next (<anonymous>)
    at deref (/Users/clement/Dev/unlock/unlock/node_modules/@openzeppelin/upgrades-core/src/ast-dereferencer.ts:30:18)
    at /Users/clement/Dev/unlock/unlock/node_modules/@openzeppelin/upgrades-core/src/utils/curry.ts:11:19
    at loadLayoutType (/Users/clement/Dev/unlock/unlock/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:137:23)
    at extractStorageLayout (/Users/clement/Dev/unlock/unlock/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:48:7)
    at validate (/Users/clement/Dev/unlock/unlock/node_modules/@openzeppelin/upgrades-core/src/validate/run.ts:173:54)
    at OverriddenTaskDefinition._action (/Users/xxx/Dev/unlock/unlock/node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:82:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    ```

**Comment by frangio** [comment]
@clemsos Sorry about this issue. I'm not sure what could've caused this. Unfortunately I can't reproduce it, after cloning your repo I'm able to compile successfully. Please try `hardhat clean` and compiling again.

**Comment by clemsos** [comment]
Thanks @frangio for the answer! 

I reverted the changes on master but you should be able to reproduce by checking the 'fix-oz-upgrade' branch https://github.com/unlock-protocol/unlock/pull/10260

**Comment by frangio** [comment]
Ok thanks I can see the error there.

**Comment by frangio** [comment]
Confirmed fixed after a patch to the `solidity-ast` dependency. Please reinstall or update to make sure you're using the latest version of that module, which is [v0.4.36](https://github.com/OpenZeppelin/solidity-ast/releases/tag/v0.4.36).

**Comment by clemsos** [comment]
Thank you very much for the prompt fix !
