### ISSUE TITLE
Error: `ValidationsCacheOutdated` since hardhat-upgrades `1.20`

### ISSUE THREAD

**Issue by marceljay** [OpenZeppelin/openzeppelin-upgrades#692]
There is a compilation issue that occurs since upgrading `@openzeppelin/hardhat-upgrades` to `1.20`

System setup:
```
    "hardhat": "2.12.2",
    "hardhat-deploy": "^0.11.19",
```

Error log from issue during `hardhat compile` (with `hardhat compile --force` the same error occurs):
```
ValidationsCacheOutdated [Error]: Validations cache is outdated. Recompile with `hardhat compile --force`
    at readValidations (/devpackages/hardhat/node_modules/@openzeppelin/hardhat-upgrades/src/utils/validations.ts:52:13)
    at async writeValidations (/devpackages/hardhat/node_modules/@openzeppelin/hardhat-upgrades/src/utils/validations.ts:23:24)
    at async OverriddenTaskDefinition._action (/devpackages/hardhat/node_modules/@openzeppelin/hardhat-upgrades/src/index.ts:82:5)
    at async Environment._runTaskDefinition (/devpackages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/devpackages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async SimpleTaskDefinition.action (/devpackages/hardhat/node_modules/hardhat/src/builtin-tasks/compile.ts:962:37)
    at async Environment._runTaskDefinition (/devpackages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/devpackages/hardhat/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at async /devpackages/hardhat/node_modules/hardhat/src/builtin-tasks/compile.ts:421:28
    at async /devpackages/hardhat/node_modules/p-map/index.js:57:22
                                                                                                                  
```

Digging a little i found the function:
```
function getValidationsCachePath(hre: HardhatRuntimeEnvironment): string {
  return path.join(hre.config.paths.cache, 'validations.json');
}
```
Unfortunately i cannot find such file in my hardhat package and also don't know what it is about. Are there docs anywhere?

**Comment by frangio** [comment]
The error message says: <code>Recompile with &#96;hardhat compile --force&#96;</code>. Have you followed this instruction?

**Comment by frangio** [comment]
This is strange. But you should see a file `cache/validations.json` that you can try to delete and compile again.

**Comment by frangio** [comment]
This error shouldn't be happening. Can you share more about your setup? Are you using other plugins? What does your Hardhat config look like?

**Comment by marceljay** [comment]
The `hardhat/cache` directory gets created, but stays empty. 😳 When switching back to `1.19.0` the directory is filled with the `validations.json` and `solidity-files-cache.json`. 

And sure, the dependencies in our hardhat package of the monorepo are:

```
  "dependencies": {
    "@abacus-network/sdk": "^0.2.4",
    "@apollo/client": "^3.4.15",
    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@0.3.0-beta.13",
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "@openzeppelin/contracts": "^4.6.0",
    "@openzeppelin/contracts-upgradeable": "^4.6.0",
    "@openzeppelin/hardhat-defender": "^1.7.0",
    "@openzeppelin/hardhat-upgrades": "^1.20.0",
    "@tenderly/hardhat-tenderly": "^1.0.10",
    "@toucan/common": "^1.0.1", 
    "axios": "^0.26.0",
    "bip39": "^3.0.4",
    "chai-as-promised": "^7.1.1",
    "chalk": "^4.1.0",
    "defender-admin-client": "^1.18.0",
    "defender-base-client": "^1.18.0",
    "dotenv": "^10.0.0",
    "enquirer": "^2.3.6",
    "ethereum-waffle": "^4.0.7",
    "ethereumjs-util": "^7.1.3",
    "ethers": "^5.7.1",
    "fp-ts": "^2.11.8",
    "graphql": "^15.0.0",
    "hardhat": "2.12.0",
    "hardhat-deploy": "^0.11.15",
    "io-ts": "^2.2.16",
    "md5": "^2.3.0",
    "mustache": "^4.2.0",
    "node-watch": "^0.7.0",
    "qrcode-terminal": "^0.12.0",
    "urql": "^2.2.0"
  },
  "devDependencies": {
    "@abacus-network/hardhat": "^0.2.4",
    "@nomiclabs/hardhat-ganache": "^2.0.1",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@types/chai": "^4.2.22",
    "@types/filesystem": "^0.0.32",
    "@types/fs-extra": "^9.0.13",
    "@types/graphql": "^14.5.0",
    "@types/keccak": "^3.0.1",
    "@types/mocha": "^9.0.0",
    "@types/node": "^16.11.0",
    "@types/qrcode-terminal": "^0.12.0",
    "chai": "^4.3.4",
    "coveralls": "^3.1.1",
    "eslint": "^7.5.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-babel": "^5.3.1",
    "hardhat-contract-sizer": "^2.5.1",
    "hardhat-gas-reporter": "^1.0.8",
    "hardhat-storage-layout": "^0.1.6",
    "solhint": "^3.3.6",
    "solidity-coverage": "^0.8.2",
    "ts-node": "^10.7.0",
    "typescript": "^4.4.4"
  }
  ```

**Comment by frangio** [comment]
Would you mind sharing your Hardhat config file, or at least the requires/imports of plugins?

**Comment by 0xmichalis** [comment]
@frangio this is the latest version of our HH imports and package.json files:
```ts
import fs from 'fs';
import { HardhatUserConfig } from 'hardhat/config';
import 'hardhat-contract-sizer';
import 'hardhat-deploy';
import 'hardhat-gas-reporter';
import 'hardhat-storage-layout';
import { HardhatNetworkForkingUserConfig, NetworkUserConfig } from 'hardhat/types';
import 'solidity-coverage';
import '@nomiclabs/hardhat-etherscan';
// @abacus-network/hardhat must be imported before 'hardhat-ethers'
// Otherwise deploy scripts (hardhat-deploy) will break
import '@abacus-network/hardhat';
import '@nomiclabs/hardhat-ethers';
import '@nomiclabs/hardhat-waffle';
import '@nomiclabs/hardhat-ganache';
import '@openzeppelin/hardhat-defender';
import '@openzeppelin/hardhat-upgrades';
import '@tenderly/hardhat-tenderly';
```
```json
"dependencies": {
    "@abacus-network/sdk": "^0.2.4",
    "@apollo/client": "^3.4.15",
    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@0.3.0-beta.13",
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "@openzeppelin/contracts": "^4.6.0",
    "@openzeppelin/contracts-upgradeable": "^4.6.0",
    "@openzeppelin/hardhat-defender": "^1.7.0",
    "@openzeppelin/hardhat-upgrades": "^1.22.0",
    "@openzeppelin/upgrades-core": "^1.20.0",
    "@tenderly/hardhat-tenderly": "^1.0.10",
    "@toucan/common": "^1.0.1",
    "axios": "^0.26.0",
    "bip39": "^3.0.4",
    "chai-as-promised": "^7.1.1",
    "chalk": "^4.1.0",
    "defender-admin-client": "^1.18.0",
    "defender-base-client": "^1.18.0",
    "dotenv": "^10.0.0",
    "enquirer": "^2.3.6",
    "ethereum-waffle": "^4.0.7",
    "ethereumjs-util": "^7.1.3",
    "ethers": "^5.7.1",
    "fp-ts": "^2.11.8",
    "graphql": "^15.0.0",
    "hardhat": "2.12.0",
    "hardhat-deploy": "^0.11.15",
    "io-ts": "^2.2.16",
    "md5": "^2.3.0",
    "mustache": "^4.2.0",
    "node-watch": "^0.7.0",
    "octokit": "^2.0.10",
    "qrcode-terminal": "^0.12.0",
    "urql": "^2.2.0"
  },
  "devDependencies": {
    "@abacus-network/hardhat": "^0.2.4",
    "@nomiclabs/hardhat-ganache": "^2.0.1",
    "@nomiclabs/hardhat-solhint": "^2.0.0",
    "@types/chai": "^4.2.22",
    "@types/filesystem": "^0.0.32",
    "@types/fs-extra": "^9.0.13",
    "@types/graphql": "^14.5.0",
    "@types/keccak": "^3.0.1",
    "@types/mocha": "^9.0.0",
    "@types/node": "^16.11.0",
    "@types/qrcode-terminal": "^0.12.0",
    "chai": "^4.3.4",
    "coveralls": "^3.1.1",
    "eslint": "^7.5.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-babel": "^5.3.1",
    "hardhat-contract-sizer": "^2.5.1",
    "hardhat-gas-reporter": "^1.0.8",
    "hardhat-storage-layout": "^0.1.6",
    "solhint": "^3.3.6",
    "solidity-coverage": "^0.8.2",
    "ts-node": "^10.7.0",
    "typescript": "^4.4.4"
  }
```

**Comment by 0xmichalis** [comment]
It seems that bumping `hardhat-defender` from `1.7.0` to `1.8.1` fixes the issue.
