### ISSUE TITLE
Cannot consume entire gap and add new gap at the same time

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-upgrades#703]
Consider the following storage layouts for V1, V2, V3:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";

contract V1 is ERC721Upgradeable {
    uint256[50] private __gap;

    // functions
}
```

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721URIStorageUpgradeable.sol";

contract V2 is ERC721Upgradeable, ERC721URIStorageUpgradeable {

    // functions
}
```

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721URIStorageUpgradeable.sol";

contract V3 is ERC721Upgradeable, ERC721URIStorageUpgradeable {
    uint256 abc;
    uint256[49] private __gap;

    // functions
}
```

This sequence should be allowed because V1 has a 50 slot gap, V2 adds ERC721URIStorageUpgradeable in the inheritance list which consumes the 50 slot gap, and V3 adds an additional variable and a new gap at the end of the storage layout.

Upgrading from V1 to V2 to V3 works.

However, if we upgrade directly from V1 to V3, Hardhat Upgrades gives the following error:
```
     Error: New storage layout is incompatible

contracts/V3.sol:9: Upgraded `__gap` to an incompatible type
  - Bad storage gap resize from 50 to 49
    Size decrease must match with corresponding variable inserts
  > Set __gap array to size -1
      at assertStorageUpgradeSafe (node_modules/@openzeppelin/upgrades-core/src/storage/index.ts:35:11)
      at Proxy.validateUpgrade (node_modules/@openzeppelin/hardhat-upgrades/src/validate-upgrade.ts:44:33)
``` 

Similarly, if V3 had gap size 50 and no `abc`, Hardhat Upgrades gives the following error, which is correct but could be more flexible to treat the original gap as consumed and allow the new gap:
```
     Error: New storage layout is incompatible

contracts/V3.sol:9: Layout changed for `__gap` (uint256[50] -> uint256[50])
  - Slot changed from 151 to 201
  > Set __gap array to size 0
      at assertStorageUpgradeSafe (node_modules/@openzeppelin/upgrades-core/src/storage/index.ts:35:11)
      at Proxy.validateUpgrade (node_modules/@openzeppelin/hardhat-upgrades/src/validate-upgrade.ts:44:33)
```

**Comment by ericglau** [comment]
Related: the following should also be allowed, but causes the error below.  The costs for the storage comparison may need to be adjusted to handle this properly.
```
contract V1Storage {
    uint256[50] private __gap;
}

contract V1 is V1Storage, ERC721Upgradeable {

    // functions
}
```

```
contract V2Storage {
    uint256 abc;
    uint256[49] private __gap;
}

contract V2 is V2Storage, ERC721Upgradeable, ERC721URIStorageUpgradeable {

    // functions
}
```
This causes the error:
```
     Error: New storage layout is incompatible

@openzeppelin/contracts-upgradeable/token/ERC721/extensions/ERC721URIStorageUpgradeable.sol:74: Upgraded `__gap` to an incompatible type
  - Bad storage gap resize from 44 to 49
    Size cannot increase
```
