### ISSUE TITLE
Error: missing arguemnt: types/values length mismatch (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=6.6.3)

### ISSUE THREAD

**Issue by samyogdhital** [OpenZeppelin/openzeppelin-upgrades#847]
Full Error 

```
> yarn run v1.22.19
$ hardhat run scripts/deploy.ts
step 1
Error: missing arguemnt: types/values length mismatch (count=0, expectedCount=1, code=MISSING_ARGUMENT, version=6.6.3)
    at makeError (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\ethers\src.ts\utils\errors.ts:677:21)
    at assert (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\ethers\src.ts\utils\errors.ts:694:25)
    at assertArgumentCount (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\ethers\src.ts\utils\errors.ts:713:5)
    at AbiCoder.encode (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\ethers\src.ts\abi\abi-coder.ts:189:28)
    at Interface._encodeParams (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\ethers\src.ts\abi\interface.ts:795:31)
    at Interface.encodeDeploy (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\ethers\src.ts\abi\interface.ts:803:21)
    at getDeployData (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\@openzeppelin\hardhat-upgrades\src\utils\deploy-impl.ts:47:45)
    at async deployProxyImpl (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\@openzeppelin\hardhat-upgrades\src\utils\deploy-impl.ts:71:22)
    at async Proxy.deployProxy (C:\Users\dhita\Desktop\xtrembet\protocol\node_modules\@openzeppelin\hardhat-upgrades\src\deploy-proxy.ts:46:28)
    at async main (C:\Users\dhita\Desktop\xtrembet\protocol\scripts\deploy.ts:13:26) {
  code: 'MISSING_ARGUMENT',
  count: 0,
  expectedCount: 1
}
```

Guys I am getting this error when deploying the Test.sol contract.
Test.sol 👇 

```
    pragma solidity 0.8.19;

    import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
    import "hardhat/console.sol";

     contract Test {
    IERC20 private usdcToken;

    constructor(address _usdcTokenAddress) {
        usdcToken = IERC20(_usdcTokenAddress);
    }

    function getContractBalance() external view returns (uint256) {
        return usdcToken.balanceOf(address(this));
    }

    function depositUSDC(uint256 _amount) external {
        usdcToken.transferFrom(msg.sender, address(this), _amount);
    }
    }
```
here is the deploy.ts script 👇

```
import { ethers, upgrades } from "hardhat";

 async function main() {


  const usdcAddress = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"

  const testContract = await ethers.getContractFactory("Test")
  console.log(`step 1`)

  const deployContract = await upgrades.deployProxy(testContract, [usdcAddress])
  console.log(`step 2`)

  await deployContract.waitForDeployment()


}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
```
🙂 Its would be really glad of you if we can fix this problem asap. Thanks.

Details :
Os- windows 11 home
node - 18.16.0

**Comment by ericglau** [comment]
Your contract is using a constructor, but upgradeable contracts should generally use initializers instead.  See https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#initializers 

You should import
```
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
```
and change the constructor to something like 
```
function initialize(address _usdcTokenAddress) initializer public {
```

Closing this issue but feel free to follow up here if you have questions.

**Comment by samyogdhital** [comment]
@ericglau Thanks for the advice.
